<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\ChannelRoom;

/**
 * Protobuf type <code>proto.ChannelRoom.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>PRIVATE_ROOM = 0;</code>
     */
    const PRIVATE_ROOM = 0;
    /**
     * Generated from protobuf enum <code>PUBLIC_ROOM = 1;</code>
     */
    const PUBLIC_ROOM = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\ChannelRoom_Type::class);

