<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConnectionSecuring.proto

namespace Proto\ConnectionSymmetricKeyResponse;

/**
 * Protobuf type <code>proto.ConnectionSymmetricKeyResponse.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>REJECTED = 0;</code>
     */
    const REJECTED = 0;
    /**
     * Generated from protobuf enum <code>ACCEPTED = 1;</code>
     */
    const ACCEPTED = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Proto\ConnectionSymmetricKeyResponse_Status::class);

