<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelPinMessage.proto

namespace GPBMetadata;

class ChannelPinMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8020a174368616e6e656c50696e4d6573736167652e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e" .
            "70726f746f22590a114368616e6e656c50696e4d657373616765121f0a07" .
            "7265717565737418012001280b320e2e70726f746f2e5265717565737412" .
            "0f0a07726f6f6d5f696418022001280412120a0a6d6573736167655f6964" .
            "180320012804227b0a194368616e6e656c50696e4d657373616765526573" .
            "706f6e736512210a08726573706f6e736518012001280b320f2e70726f74" .
            "6f2e526573706f6e7365120f0a07726f6f6d5f6964180220012804122a0a" .
            "0e70696e6e65645f6d65737361676518032001280b32122e70726f746f2e" .
            "526f6f6d4d65737361676542280a0e6e65742e694761702e70726f746f42" .
            "1650726f746f4368616e6e656c50696e4d657373616765620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

