<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelRevokeLink.proto

namespace GPBMetadata;

class ChannelRevokeLink
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5020a174368616e6e656c5265766f6b654c696e6b2e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22450a114368616e6e" .
            "656c5265766f6b654c696e6b121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e52657175657374120f0a07726f6f6d5f696418022001" .
            "2804227a0a194368616e6e656c5265766f6b654c696e6b526573706f6e73" .
            "6512210a08726573706f6e736518012001280b320f2e70726f746f2e5265" .
            "73706f6e7365120f0a07726f6f6d5f696418022001280412130a0b696e76" .
            "6974655f6c696e6b18032001280912140a0c696e766974655f746f6b656e" .
            "18042001280942280a0e6e65742e694761702e70726f746f421650726f74" .
            "6f4368616e6e656c5265766f6b654c696e6b620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

