<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelDelete.proto

namespace GPBMetadata;

class ChannelDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea010a134368616e6e656c44656c6574652e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f22410a0d4368616e6e656c4465" .
            "6c657465121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120f0a07726f6f6d5f6964180220012804224b0a154368" .
            "616e6e656c44656c657465526573706f6e736512210a08726573706f6e73" .
            "6518012001280b320f2e70726f746f2e526573706f6e7365120f0a07726f" .
            "6f6d5f696418022001280442240a0e6e65742e694761702e70726f746f42" .
            "1250726f746f4368616e6e656c44656c657465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

