<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelCreate.proto

namespace GPBMetadata;

class ChannelCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a134368616e6e656c4372656174652e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f22530a0d4368616e6e656c4372" .
            "65617465121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120c0a046e616d6518022001280912130a0b6465736372" .
            "697074696f6e18032001280922600a154368616e6e656c43726561746552" .
            "6573706f6e736512210a08726573706f6e736518012001280b320f2e7072" .
            "6f746f2e526573706f6e7365120f0a07726f6f6d5f696418022001280412" .
            "130a0b696e766974655f6c696e6b18032001280942240a0e6e65742e6947" .
            "61702e70726f746f421250726f746f4368616e6e656c4372656174656206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

