<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelUpdateUsername.proto

namespace GPBMetadata;

class ChannelUpdateUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae020a1b4368616e6e656c557064617465557365726e616d652e70726f" .
            "746f120570726f746f1a0e526573706f6e73652e70726f746f225b0a1543" .
            "68616e6e656c557064617465557365726e616d65121f0a07726571756573" .
            "7418012001280b320e2e70726f746f2e5265717565737412100a08757365" .
            "726e616d65180220012809120f0a07726f6f6d5f69641803200128042265" .
            "0a1d4368616e6e656c557064617465557365726e616d65526573706f6e73" .
            "6512210a08726573706f6e736518012001280b320f2e70726f746f2e5265" .
            "73706f6e736512100a08757365726e616d65180220012809120f0a07726f" .
            "6f6d5f6964180320012804422c0a0e6e65742e694761702e70726f746f42" .
            "1a50726f746f4368616e6e656c557064617465557365726e616d65620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

