<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetDraft.proto

namespace GPBMetadata;

class ChannelGetDraft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90020a154368616e6e656c47657444726166742e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e7072" .
            "6f746f22430a0f4368616e6e656c4765744472616674121f0a0772657175" .
            "65737418012001280b320e2e70726f746f2e52657175657374120f0a0772" .
            "6f6f6d5f6964180220012804225d0a174368616e6e656c47657444726166" .
            "74526573706f6e736512210a08726573706f6e736518012001280b320f2e" .
            "70726f746f2e526573706f6e7365121f0a05647261667418022001280b32" .
            "102e70726f746f2e526f6f6d447261667442260a0e6e65742e694761702e" .
            "70726f746f421450726f746f4368616e6e656c4765744472616674620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

