<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelAvatarDelete.proto

namespace GPBMetadata;

class ChannelAvatarDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a020a194368616e6e656c41766174617244656c6574652e70726f746f" .
            "120570726f746f1a0e526573706f6e73652e70726f746f22530a13436861" .
            "6e6e656c41766174617244656c657465121f0a0772657175657374180120" .
            "01280b320e2e70726f746f2e52657175657374120a0a0269641802200128" .
            "04120f0a07726f6f6d5f6964180320012804225d0a1b4368616e6e656c41" .
            "766174617244656c657465526573706f6e736512210a08726573706f6e73" .
            "6518012001280b320f2e70726f746f2e526573706f6e7365120a0a026964" .
            "180220012804120f0a07726f6f6d5f6964180320012804422a0a0e6e6574" .
            "2e694761702e70726f746f421850726f746f4368616e6e656c4176617461" .
            "7244656c657465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

