<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatGetDraft.proto

namespace GPBMetadata;

class ChatGetDraft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a124368617447657444726166742e70726f746f120570726f746f" .
            "1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f746f" .
            "22400a0c436861744765744472616674121f0a0772657175657374180120" .
            "01280b320e2e70726f746f2e52657175657374120f0a07726f6f6d5f6964" .
            "180220012804225a0a14436861744765744472616674526573706f6e7365" .
            "12210a08726573706f6e736518012001280b320f2e70726f746f2e526573" .
            "706f6e7365121f0a05647261667418022001280b32102e70726f746f2e52" .
            "6f6f6d447261667442230a0e6e65742e694761702e70726f746f42115072" .
            "6f746f436861744765744472616674620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

