<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatUpdateDraft.proto

namespace GPBMetadata;

class ChatUpdateDraft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac2020a154368617455706461746544726166742e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e7072" .
            "6f746f22640a0f436861745570646174654472616674121f0a0772657175" .
            "65737418012001280b320e2e70726f746f2e52657175657374120f0a0772" .
            "6f6f6d5f6964180220012804121f0a05647261667418032001280b32102e" .
            "70726f746f2e526f6f6d4472616674226e0a174368617455706461746544" .
            "72616674526573706f6e736512210a08726573706f6e736518012001280b" .
            "320f2e70726f746f2e526573706f6e7365120f0a07726f6f6d5f69641802" .
            "20012804121f0a05647261667418032001280b32102e70726f746f2e526f" .
            "6f6d447261667442260a0e6e65742e694761702e70726f746f421450726f" .
            "746f436861745570646174654472616674620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

