<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatDelete.proto

namespace GPBMetadata;

class ChatDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a104368617444656c6574652e70726f746f120570726f746f1a0e" .
            "526573706f6e73652e70726f746f223e0a0a4368617444656c657465121f" .
            "0a077265717565737418012001280b320e2e70726f746f2e526571756573" .
            "74120f0a07726f6f6d5f696418022001280422480a124368617444656c65" .
            "7465526573706f6e736512210a08726573706f6e736518012001280b320f" .
            "2e70726f746f2e526573706f6e7365120f0a07726f6f6d5f696418022001" .
            "280442210a0e6e65742e694761702e70726f746f420f50726f746f436861" .
            "7444656c657465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

