<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatDeleteMessage.proto

namespace GPBMetadata;

class ChatDeleteMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8020a174368617444656c6574654d6573736167652e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22670a114368617444" .
            "656c6574654d657373616765121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e52657175657374120f0a07726f6f6d5f696418022001" .
            "280412120a0a6d6573736167655f6964180320012804120c0a04626f7468" .
            "180420012808227b0a194368617444656c6574654d657373616765526573" .
            "706f6e736512210a08726573706f6e736518012001280b320f2e70726f74" .
            "6f2e526573706f6e7365120f0a07726f6f6d5f696418022001280412120a" .
            "0a6d6573736167655f696418032001280412160a0e64656c6574655f7665" .
            "7273696f6e18042001280442280a0e6e65742e694761702e70726f746f42" .
            "1650726f746f4368617444656c6574654d657373616765620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

