<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatEditMessage.proto

namespace GPBMetadata;

class ChatEditMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92030a1543686174456469744d6573736167652e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e7072" .
            "6f746f22680a0f43686174456469744d657373616765121f0a0772657175" .
            "65737418012001280b320e2e70726f746f2e52657175657374120f0a0772" .
            "6f6f6d5f696418022001280412120a0a6d6573736167655f696418032001" .
            "2804120f0a076d65737361676518042001280922b9010a17436861744564" .
            "69744d657373616765526573706f6e736512210a08726573706f6e736518" .
            "012001280b320f2e70726f746f2e526573706f6e7365120f0a07726f6f6d" .
            "5f696418022001280412120a0a6d6573736167655f696418032001280412" .
            "170a0f6d6573736167655f76657273696f6e180420012804120f0a076d65" .
            "7373616765180520012809122c0a0c6d6573736167655f74797065180620" .
            "01280e32162e70726f746f2e526f6f6d4d6573736167655479706542260a" .
            "0e6e65742e694761702e70726f746f421450726f746f4368617445646974" .
            "4d657373616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

