<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatUpdateStatus.proto

namespace GPBMetadata;

class ChatUpdateStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7030a16436861745570646174655374617475732e70726f746f120570" .
            "726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70" .
            "726f746f2282010a1043686174557064617465537461747573121f0a0772" .
            "65717565737418012001280b320e2e70726f746f2e52657175657374120f" .
            "0a07726f6f6d5f696418022001280412120a0a6d6573736167655f696418" .
            "032001280412280a0673746174757318042001280e32182e70726f746f2e" .
            "526f6f6d4d65737361676553746174757322c1010a184368617455706461" .
            "7465537461747573526573706f6e736512210a08726573706f6e73651801" .
            "2001280b320f2e70726f746f2e526573706f6e7365120f0a07726f6f6d5f" .
            "696418022001280412120a0a6d6573736167655f69641803200128041228" .
            "0a0673746174757318042001280e32182e70726f746f2e526f6f6d4d6573" .
            "7361676553746174757312160a0e7374617475735f76657273696f6e1805" .
            "20012804121b0a13757064617465725f617574686f725f68617368180620" .
            "01280942270a0e6e65742e694761702e70726f746f421550726f746f4368" .
            "6174557064617465537461747573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

