<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetRoomHistory.proto

namespace GPBMetadata;

class ClientGetRoomHistory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab030a1a436c69656e74476574526f6f6d486973746f72792e70726f74" .
            "6f120570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62" .
            "616c2e70726f746f22ca010a14436c69656e74476574526f6f6d48697374" .
            "6f7279121f0a077265717565737418012001280b320e2e70726f746f2e52" .
            "657175657374120f0a07726f6f6d5f696418022001280412180a10666972" .
            "73745f6d6573736167655f696418032001280412380a0964697265637469" .
            "6f6e18042001280e32252e70726f746f2e436c69656e74476574526f6f6d" .
            "486973746f72792e446972656374696f6e120d0a056c696d697418052001" .
            "280d221d0a09446972656374696f6e12060a025550100012080a04444f57" .
            "4e100122660a1c436c69656e74476574526f6f6d486973746f7279526573" .
            "706f6e736512210a08726573706f6e736518012001280b320f2e70726f74" .
            "6f2e526573706f6e736512230a076d65737361676518022003280b32122e" .
            "70726f746f2e526f6f6d4d657373616765422b0a0e6e65742e694761702e" .
            "70726f746f421950726f746f436c69656e74476574526f6f6d486973746f" .
            "7279620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

