<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetRoom.proto

namespace GPBMetadata;

class ClientGetRoom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82020a13436c69656e74476574526f6f6d2e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f74" .
            "6f22410a0d436c69656e74476574526f6f6d121f0a077265717565737418" .
            "012001280b320e2e70726f746f2e52657175657374120f0a07726f6f6d5f" .
            "696418022001280422550a15436c69656e74476574526f6f6d526573706f" .
            "6e736512210a08726573706f6e736518012001280b320f2e70726f746f2e" .
            "526573706f6e736512190a04726f6f6d18022001280b320b2e70726f746f" .
            "2e526f6f6d42240a0e6e65742e694761702e70726f746f421250726f746f" .
            "436c69656e74476574526f6f6d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

