<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientPinRoom.proto

namespace GPBMetadata;

class ClientPinRoom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87020a13436c69656e7450696e526f6f6d2e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f224e0a0d436c69656e7450696e" .
            "526f6f6d121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120f0a07726f6f6d5f6964180220012804120b0a037069" .
            "6e180320012808225b0a15436c69656e7450696e526f6f6d526573706f6e" .
            "736512210a08726573706f6e736518012001280b320f2e70726f746f2e52" .
            "6573706f6e7365120f0a07726f6f6d5f6964180220012804120e0a067069" .
            "6e5f696418032001280442240a0e6e65742e694761702e70726f746f4212" .
            "50726f746f436c69656e7450696e526f6f6d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

