<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetRoomMessage.proto

namespace GPBMetadata;

class ClientGetRoomMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abc020a1a436c69656e74476574526f6f6d4d6573736167652e70726f74" .
            "6f120570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62" .
            "616c2e70726f746f225c0a14436c69656e74476574526f6f6d4d65737361" .
            "6765121f0a077265717565737418012001280b320e2e70726f746f2e5265" .
            "7175657374120f0a07726f6f6d5f696418022001280412120a0a6d657373" .
            "6167655f696418032001280422660a1c436c69656e74476574526f6f6d4d" .
            "657373616765526573706f6e736512210a08726573706f6e736518012001" .
            "280b320f2e70726f746f2e526573706f6e736512230a076d657373616765" .
            "18022001280b32122e70726f746f2e526f6f6d4d657373616765422b0a0e" .
            "6e65742e694761702e70726f746f421950726f746f436c69656e74476574" .
            "526f6f6d4d657373616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

