<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientJoinByUsername.proto

namespace GPBMetadata;

class ClientJoinByUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a1a436c69656e744a6f696e4279557365726e616d652e70726f74" .
            "6f120570726f746f1a0e526573706f6e73652e70726f746f22490a14436c" .
            "69656e744a6f696e4279557365726e616d65121f0a077265717565737418" .
            "012001280b320e2e70726f746f2e5265717565737412100a08757365726e" .
            "616d6518022001280922410a1c436c69656e744a6f696e4279557365726e" .
            "616d65526573706f6e736512210a08726573706f6e736518012001280b32" .
            "0f2e70726f746f2e526573706f6e7365422b0a0e6e65742e694761702e70" .
            "726f746f421950726f746f436c69656e744a6f696e4279557365726e616d" .
            "65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

