<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMuteRoom.proto

namespace GPBMetadata;

class ClientMuteRoom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4020a14436c69656e744d757465526f6f6d2e70726f746f120570726f" .
            "746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f" .
            "746f22660a0e436c69656e744d757465526f6f6d121f0a07726571756573" .
            "7418012001280b320e2e70726f746f2e52657175657374120f0a07726f6f" .
            "6d5f696418022001280412220a09726f6f6d5f6d75746518032001280e32" .
            "0f2e70726f746f2e526f6f6d4d75746522700a16436c69656e744d757465" .
            "526f6f6d526573706f6e736512210a08726573706f6e736518012001280b" .
            "320f2e70726f746f2e526573706f6e7365120f0a07726f6f6d5f69641802" .
            "2001280412220a09726f6f6d5f6d75746518032001280e320f2e70726f74" .
            "6f2e526f6f6d4d75746542250a0e6e65742e694761702e70726f746f4213" .
            "50726f746f436c69656e744d757465526f6f6d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

