<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetRoomList.proto

namespace GPBMetadata;

class ClientGetRoomList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa9020a17436c69656e74476574526f6f6d4c6973742e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e" .
            "70726f746f225b0a11436c69656e74476574526f6f6d4c697374121f0a07" .
            "7265717565737418012001280b320e2e70726f746f2e5265717565737412" .
            "250a0a706167696e6174696f6e18022001280b32112e70726f746f2e5061" .
            "67696e6174696f6e225a0a19436c69656e74476574526f6f6d4c69737452" .
            "6573706f6e736512210a08726573706f6e736518012001280b320f2e7072" .
            "6f746f2e526573706f6e7365121a0a05726f6f6d7318022003280b320b2e" .
            "70726f746f2e526f6f6d42280a0e6e65742e694761702e70726f746f4216" .
            "50726f746f436c69656e74476574526f6f6d4c697374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

