<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientUnsubscribeFromRoom.proto

namespace GPBMetadata;

class ClientUnsubscribeFromRoom
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89020a1f436c69656e74556e73756273637269626546726f6d526f6f6d" .
            "2e70726f746f120570726f746f1a0e526573706f6e73652e70726f746f22" .
            "4d0a19436c69656e74556e73756273637269626546726f6d526f6f6d121f" .
            "0a077265717565737418012001280b320e2e70726f746f2e526571756573" .
            "74120f0a07726f6f6d5f696418022001280422460a21436c69656e74556e" .
            "73756273637269626546726f6d526f6f6d526573706f6e736512210a0872" .
            "6573706f6e736518012001280b320f2e70726f746f2e526573706f6e7365" .
            "42300a0e6e65742e694761702e70726f746f421e50726f746f436c69656e" .
            "74556e73756273637269626546726f6d526f6f6d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

