<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientResolveUsername.proto

namespace GPBMetadata;

class ClientResolveUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e030a1b436c69656e745265736f6c7665557365726e616d652e70726f" .
            "746f120570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f" .
            "62616c2e70726f746f224a0a15436c69656e745265736f6c766555736572" .
            "6e616d65121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "5265717565737412100a08757365726e616d6518022001280922d7010a1d" .
            "436c69656e745265736f6c7665557365726e616d65526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e736512370a047479706518022001280e32292e70726f746f2e436c69" .
            "656e745265736f6c7665557365726e616d65526573706f6e73652e547970" .
            "6512230a047573657218032001280b32152e70726f746f2e526567697374" .
            "657265645573657212190a04726f6f6d18042001280b320b2e70726f746f" .
            "2e526f6f6d221a0a045479706512080a0455534552100012080a04524f4f" .
            "4d1001422c0a0e6e65742e694761702e70726f746f421a50726f746f436c" .
            "69656e745265736f6c7665557365726e616d65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

