<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Error.proto

namespace GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a0b4572726f722e70726f746f120570726f746f22790a0d457272" .
            "6f72526573706f6e736512210a08726573706f6e736518012001280b320f" .
            "2e70726f746f2e526573706f6e736512120a0a6d616a6f725f636f646518" .
            "022001280d12120a0a6d696e6f725f636f646518032001280d120c0a0477" .
            "61697418042001280d120f0a076d657373616765180520012809421c0a0e" .
            "6e65742e694761702e70726f746f420a50726f746f4572726f7262067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

