<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileUploadInit.proto

namespace GPBMetadata;

class FileUploadInit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea020a1446696c6555706c6f6164496e69742e70726f746f120570726f" .
            "746f1a0e526573706f6e73652e70726f746f228e010a0e46696c6555706c" .
            "6f6164496e6974121f0a077265717565737418012001280b320e2e70726f" .
            "746f2e5265717565737412130a0b66697273745f62797465731802200128" .
            "0c12120a0a6c6173745f627974657318032001280c120c0a0473697a6518" .
            "042001280312110a0966696c655f6861736818052001280c12110a096669" .
            "6c655f6e616d65180620012809227b0a1646696c6555706c6f6164496e69" .
            "74526573706f6e736512210a08726573706f6e736518012001280b320f2e" .
            "70726f746f2e526573706f6e7365120d0a05746f6b656e18022001280912" .
            "100a0870726f6772657373180320012801120e0a066f6666736574180420" .
            "012803120d0a056c696d697418052001280542250a0e6e65742e69476170" .
            "2e70726f746f421350726f746f46696c6555706c6f6164496e6974620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

