<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileDownload.proto

namespace GPBMetadata;

class FileDownload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e030a1246696c65446f776e6c6f61642e70726f746f120570726f746f" .
            "1a0e526573706f6e73652e70726f746f22e9010a0c46696c65446f776e6c" .
            "6f6164121f0a077265717565737418012001280b320e2e70726f746f2e52" .
            "657175657374120d0a05746f6b656e180220012809120e0a066f66667365" .
            "7418032001280312110a096d61785f6c696d6974180420012805122e0a08" .
            "73656c6563746f7218052001280e321c2e70726f746f2e46696c65446f77" .
            "6e6c6f61642e53656c6563746f7222560a0853656c6563746f7212080a04" .
            "46494c45100012130a0f534d414c4c5f5448554d424e41494c100112130a" .
            "0f4c415247455f5448554d424e41494c100212160a1257415645464f524d" .
            "5f5448554d424e41494c100322480a1446696c65446f776e6c6f61645265" .
            "73706f6e736512210a08726573706f6e736518012001280b320f2e70726f" .
            "746f2e526573706f6e7365120d0a05627974657318042001280c42230a0e" .
            "6e65742e694761702e70726f746f421150726f746f46696c65446f776e6c" .
            "6f6164620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

