<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileInfo.proto

namespace GPBMetadata;

class FileInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aec010a0e46696c65496e666f2e70726f746f120570726f746f1a0e5265" .
            "73706f6e73652e70726f746f1a0c476c6f62616c2e70726f746f223a0a08" .
            "46696c65496e666f121f0a077265717565737418012001280b320e2e7072" .
            "6f746f2e52657175657374120d0a05746f6b656e18022001280922500a10" .
            "46696c65496e666f526573706f6e736512210a08726573706f6e73651801" .
            "2001280b320f2e70726f746f2e526573706f6e736512190a0466696c6518" .
            "022001280b320b2e70726f746f2e46696c65421f0a0e6e65742e69476170" .
            "2e70726f746f420d50726f746f46696c65496e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

