<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeoGetConfiguration.proto

namespace GPBMetadata;

class GeoGetConfiguration
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7020a1947656f476574436f6e66696775726174696f6e2e70726f746f" .
            "120570726f746f1a0e526573706f6e73652e70726f746f22360a1347656f" .
            "476574436f6e66696775726174696f6e121f0a0772657175657374180120" .
            "01280b320e2e70726f746f2e5265717565737422b6010a1b47656f476574" .
            "436f6e66696775726174696f6e526573706f6e736512210a08726573706f" .
            "6e736518012001280b320f2e70726f746f2e526573706f6e736512420a0b" .
            "74696c655f73657276657218022003280b322d2e70726f746f2e47656f47" .
            "6574436f6e66696775726174696f6e526573706f6e73652e54696c655365" .
            "7276657212100a0863616368655f69641803200128091a1e0a0a54696c65" .
            "53657276657212100a08626173655f75726c180120012809422a0a0e6e65" .
            "742e694761702e70726f746f421850726f746f47656f476574436f6e6669" .
            "6775726174696f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

