<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeoGetRegisterStatus.proto

namespace GPBMetadata;

class GeoGetRegisterStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a1a47656f47657452656769737465725374617475732e70726f74" .
            "6f120570726f746f1a0e526573706f6e73652e70726f746f22370a144765" .
            "6f4765745265676973746572537461747573121f0a077265717565737418" .
            "012001280b320e2e70726f746f2e5265717565737422510a1c47656f4765" .
            "745265676973746572537461747573526573706f6e736512210a08726573" .
            "706f6e736518012001280b320f2e70726f746f2e526573706f6e7365120e" .
            "0a06656e61626c65180220012808422b0a0e6e65742e694761702e70726f" .
            "746f421950726f746f47656f476574526567697374657253746174757362" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

