<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeoGetComment.proto

namespace GPBMetadata;

class GeoGetComment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aea010a1347656f476574436f6d6d656e742e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f22410a0d47656f476574436f6d" .
            "6d656e74121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120f0a07757365725f6964180220012804224b0a154765" .
            "6f476574436f6d6d656e74526573706f6e736512210a08726573706f6e73" .
            "6518012001280b320f2e70726f746f2e526573706f6e7365120f0a07636f" .
            "6d6d656e7418022001280942240a0e6e65742e694761702e70726f746f42" .
            "1250726f746f47656f476574436f6d6d656e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

