<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GeoUpdateComment.proto

namespace GPBMetadata;

class GeoUpdateComment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6010a1647656f557064617465436f6d6d656e742e70726f746f120570" .
            "726f746f1a0e526573706f6e73652e70726f746f22440a1047656f557064" .
            "617465436f6d6d656e74121f0a077265717565737418012001280b320e2e" .
            "70726f746f2e52657175657374120f0a07636f6d6d656e74180220012809" .
            "224e0a1847656f557064617465436f6d6d656e74526573706f6e73651221" .
            "0a08726573706f6e736518012001280b320f2e70726f746f2e526573706f" .
            "6e7365120f0a07636f6d6d656e7418022001280942270a0e6e65742e6947" .
            "61702e70726f746f421550726f746f47656f557064617465436f6d6d656e" .
            "74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

