<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAddAdmin.proto

namespace GPBMetadata;

class GroupAddAdmin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90020a1347726f757041646441646d696e2e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f22540a0d47726f757041646441" .
            "646d696e121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120f0a07726f6f6d5f696418022001280412110a096d65" .
            "6d6265725f6964180320012804225e0a1547726f757041646441646d696e" .
            "526573706f6e736512210a08726573706f6e736518012001280b320f2e70" .
            "726f746f2e526573706f6e7365120f0a07726f6f6d5f6964180220012804" .
            "12110a096d656d6265725f696418032001280442240a0e6e65742e694761" .
            "702e70726f746f421250726f746f47726f757041646441646d696e620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

