<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupLeft.proto

namespace GPBMetadata;

class GroupLeft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed010a0f47726f75704c6566742e70726f746f120570726f746f1a0e52" .
            "6573706f6e73652e70726f746f223d0a0947726f75704c656674121f0a07" .
            "7265717565737418012001280b320e2e70726f746f2e5265717565737412" .
            "0f0a07726f6f6d5f6964180220012804225a0a1147726f75704c65667452" .
            "6573706f6e736512210a08726573706f6e736518012001280b320f2e7072" .
            "6f746f2e526573706f6e7365120f0a07726f6f6d5f696418022001280412" .
            "110a096d656d6265725f696418032001280442200a0e6e65742e69476170" .
            "2e70726f746f420e50726f746f47726f75704c656674620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

