<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupGetDraft.proto

namespace GPBMetadata;

class GroupGetDraft
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88020a1347726f757047657444726166742e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f74" .
            "6f22410a0d47726f75704765744472616674121f0a077265717565737418" .
            "012001280b320e2e70726f746f2e52657175657374120f0a07726f6f6d5f" .
            "6964180220012804225b0a1547726f75704765744472616674526573706f" .
            "6e736512210a08726573706f6e736518012001280b320f2e70726f746f2e" .
            "526573706f6e7365121f0a05647261667418022001280b32102e70726f74" .
            "6f2e526f6f6d447261667442240a0e6e65742e694761702e70726f746f42" .
            "1250726f746f47726f75704765744472616674620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

