<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupDeleteMessage.proto

namespace GPBMetadata;

class GroupDeleteMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a1847726f757044656c6574654d6573736167652e70726f746f12" .
            "0570726f746f1a0e526573706f6e73652e70726f746f225a0a1247726f75" .
            "7044656c6574654d657373616765121f0a07726571756573741801200128" .
            "0b320e2e70726f746f2e52657175657374120f0a07726f6f6d5f69641802" .
            "2001280412120a0a6d6573736167655f6964180320012804227c0a1a4772" .
            "6f757044656c6574654d657373616765526573706f6e736512210a087265" .
            "73706f6e736518012001280b320f2e70726f746f2e526573706f6e736512" .
            "0f0a07726f6f6d5f696418022001280412120a0a6d6573736167655f6964" .
            "18032001280412160a0e64656c6574655f76657273696f6e180420012804" .
            "42290a0e6e65742e694761702e70726f746f421750726f746f47726f7570" .
            "44656c6574654d657373616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

