<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAvatarDelete.proto

namespace GPBMetadata;

class GroupAvatarDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a92020a1747726f757041766174617244656c6574652e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22510a1147726f7570" .
            "41766174617244656c657465121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e52657175657374120a0a026964180220012804120f0a" .
            "07726f6f6d5f6964180320012804225b0a1947726f757041766174617244" .
            "656c657465526573706f6e736512210a08726573706f6e73651801200128" .
            "0b320f2e70726f746f2e526573706f6e7365120a0a026964180220012804" .
            "120f0a07726f6f6d5f696418032001280442280a0e6e65742e694761702e" .
            "70726f746f421650726f746f47726f757041766174617244656c65746562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

