<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupUpdateUsername.proto

namespace GPBMetadata;

class GroupUpdateUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6020a1947726f7570557064617465557365726e616d652e70726f746f" .
            "120570726f746f1a0e526573706f6e73652e70726f746f22590a1347726f" .
            "7570557064617465557365726e616d65121f0a0772657175657374180120" .
            "01280b320e2e70726f746f2e5265717565737412100a08757365726e616d" .
            "65180220012809120f0a07726f6f6d5f696418032001280422630a1b4772" .
            "6f7570557064617465557365726e616d65526573706f6e736512210a0872" .
            "6573706f6e736518012001280b320f2e70726f746f2e526573706f6e7365" .
            "12100a08757365726e616d65180220012809120f0a07726f6f6d5f696418" .
            "0320012804422a0a0e6e65742e694761702e70726f746f421850726f746f" .
            "47726f7570557064617465557365726e616d65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

