<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupPinMessage.proto

namespace GPBMetadata;

class GroupPinMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0020a1547726f757050696e4d6573736167652e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e7072" .
            "6f746f22570a0f47726f757050696e4d657373616765121f0a0772657175" .
            "65737418012001280b320e2e70726f746f2e52657175657374120f0a0772" .
            "6f6f6d5f696418022001280412120a0a6d6573736167655f696418032001" .
            "280422790a1747726f757050696e4d657373616765526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e7365120f0a07726f6f6d5f6964180220012804122a0a0e70696e6e65" .
            "645f6d65737361676518032001280b32122e70726f746f2e526f6f6d4d65" .
            "737361676542260a0e6e65742e694761702e70726f746f421450726f746f" .
            "47726f757050696e4d657373616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

