<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupGetMemberList.proto

namespace GPBMetadata;

class GroupGetMemberList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95040a1847726f75704765744d656d6265724c6973742e70726f746f12" .
            "0570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c" .
            "2e70726f746f22e5010a1247726f75704765744d656d6265724c69737412" .
            "1f0a077265717565737418012001280b320e2e70726f746f2e5265717565" .
            "7374120f0a07726f6f6d5f696418022001280412390a0b66696c7465725f" .
            "726f6c6518032001280e32242e70726f746f2e47726f75704765744d656d" .
            "6265724c6973742e46696c746572526f6c6512250a0a706167696e617469" .
            "6f6e18042001280b32112e70726f746f2e506167696e6174696f6e223b0a" .
            "0a46696c746572526f6c6512070a03414c4c1000120a0a064d454d424552" .
            "1001120d0a094d4f44455241544f52100212090a0541444d494e100322b8" .
            "010a1a47726f75704765744d656d6265724c697374526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e736512380a066d656d62657218022003280b32282e70726f746f2e47" .
            "726f75704765744d656d6265724c697374526573706f6e73652e4d656d62" .
            "65721a3d0a064d656d626572120e0a067573657249641801200128041223" .
            "0a04726f6c6518022001280e32152e70726f746f2e47726f7570526f6f6d" .
            "2e526f6c6542290a0e6e65742e694761702e70726f746f421750726f746f" .
            "47726f75704765744d656d6265724c697374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

