<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupCheckUsername.proto

namespace GPBMetadata;

class GroupCheckUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89030a1847726f7570436865636b557365726e616d652e70726f746f12" .
            "0570726f746f1a0e526573706f6e73652e70726f746f22580a1247726f75" .
            "70436865636b557365726e616d65121f0a07726571756573741801200128" .
            "0b320e2e70726f746f2e5265717565737412100a08757365726e616d6518" .
            "0220012809120f0a07726f6f6d5f696418032001280422c8010a1a47726f" .
            "7570436865636b557365726e616d65526573706f6e736512210a08726573" .
            "706f6e736518012001280b320f2e70726f746f2e526573706f6e73651238" .
            "0a0673746174757318022001280e32282e70726f746f2e47726f75704368" .
            "65636b557365726e616d65526573706f6e73652e537461747573224d0a06" .
            "537461747573120b0a07494e56414c4944100012090a0554414b454e1001" .
            "120d0a09415641494c41424c451002121c0a184f4343555059494e475f4c" .
            "494d49545f4558434545444544100342290a0e6e65742e694761702e7072" .
            "6f746f421750726f746f47726f7570436865636b557365726e616d656206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

