<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAddMember.proto

namespace GPBMetadata;

class GroupAddMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97030a1447726f75704164644d656d6265722e70726f746f120570726f" .
            "746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f" .
            "746f22a5010a0e47726f75704164644d656d626572121f0a077265717565" .
            "737418012001280b320e2e70726f746f2e52657175657374120f0a07726f" .
            "6f6d5f6964180220012804122c0a066d656d62657218032001280b321c2e" .
            "70726f746f2e47726f75704164644d656d6265722e4d656d6265721a330a" .
            "064d656d626572120f0a07757365725f696418012001280412180a107374" .
            "6172745f6d6573736167655f69641802200128042282010a1647726f7570" .
            "4164644d656d626572526573706f6e736512210a08726573706f6e736518" .
            "012001280b320f2e70726f746f2e526573706f6e7365120f0a07726f6f6d" .
            "5f6964180220012804120f0a07757365725f696418032001280412230a04" .
            "726f6c6518042001280e32152e70726f746f2e47726f7570526f6f6d2e52" .
            "6f6c6542250a0e6e65742e694761702e70726f746f421350726f746f4772" .
            "6f75704164644d656d626572620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

