<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoPage.proto

namespace GPBMetadata;

class InfoPage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace010a0e496e666f506167652e70726f746f120570726f746f1a0e5265" .
            "73706f6e73652e70726f746f22370a08496e666f50616765121f0a077265" .
            "717565737418012001280b320e2e70726f746f2e52657175657374120a0a" .
            "02696418022001280922430a10496e666f50616765526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e7365120c0a04626f6479180220012809421f0a0e6e65742e69476170" .
            "2e70726f746f420d50726f746f496e666f50616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

