<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushLoginToken.proto

namespace GPBMetadata;

class PushLoginToken
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad1010a14507573684c6f67696e546f6b656e2e70726f746f120570726f" .
            "746f2282010a16507573684c6f67696e546f6b656e526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e736512100a08757365726e616d65180220012809120f0a0775736572" .
            "5f696418032001280412130a0b617574686f725f68617368180420012809" .
            "120d0a05746f6b656e18052001280942250a0e6e65742e694761702e7072" .
            "6f746f421350726f746f507573684c6f67696e546f6b656e620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

