<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushTwoStepVerification.proto

namespace GPBMetadata;

class PushTwoStepVerification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a1d5075736854776f53746570566572696669636174696f6e2e70" .
            "726f746f120570726f746f227c0a1f5075736854776f5374657056657269" .
            "6669636174696f6e526573706f6e736512210a08726573706f6e73651801" .
            "2001280b320f2e70726f746f2e526573706f6e736512100a08757365726e" .
            "616d65180220012809120f0a07757365725f696418032001280412130a0b" .
            "617574686f725f68617368180420012809422e0a0e6e65742e694761702e" .
            "70726f746f421c50726f746f5075736854776f5374657056657269666963" .
            "6174696f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

