<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PushRateSignaling.proto

namespace GPBMetadata;

class PushRateSignaling
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e010a1750757368526174655369676e616c696e672e70726f746f1205" .
            "70726f746f224a0a1950757368526174655369676e616c696e6752657370" .
            "6f6e736512210a08726573706f6e736518012001280b320f2e70726f746f" .
            "2e526573706f6e7365120a0a02696418022001280442280a0e6e65742e69" .
            "4761702e70726f746f421650726f746f50757368526174655369676e616c" .
            "696e67620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

