<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QrCodeAddContact.proto

namespace GPBMetadata;

class QrCodeAddContact
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa1020a165172436f6465416464436f6e746163742e70726f746f120570" .
            "726f746f1a0e526573706f6e73652e70726f746f22690a105172436f6465" .
            "416464436f6e74616374121f0a077265717565737418012001280b320e2e" .
            "70726f746f2e52657175657374120d0a0570686f6e651802200128091212" .
            "0a0a66697273745f6e616d6518032001280912110a096c6173745f6e616d" .
            "6518042001280922540a185172436f6465416464436f6e74616374526573" .
            "706f6e736512210a08726573706f6e736518012001280b320f2e70726f74" .
            "6f2e526573706f6e736512150a0d71725f636f64655f696d616765180220" .
            "01280c42270a0e6e65742e694761702e70726f746f421550726f746f5172" .
            "436f6465416464436f6e74616374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

