<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QrCodeAddMe.proto

namespace GPBMetadata;

class QrCodeAddMe
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a115172436f64654164644d652e70726f746f120570726f746f1a" .
            "0e526573706f6e73652e70726f746f222e0a0b5172436f64654164644d65" .
            "121f0a077265717565737418012001280b320e2e70726f746f2e52657175" .
            "657374224f0a135172436f64654164644d65526573706f6e736512210a08" .
            "726573706f6e736518012001280b320f2e70726f746f2e526573706f6e73" .
            "6512150a0d71725f636f64655f696d61676518022001280c42220a0e6e65" .
            "742e694761702e70726f746f421050726f746f5172436f64654164644d65" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

