<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QrCodeNewDevice.proto

namespace GPBMetadata;

class QrCodeNewDevice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ace030a155172436f64654e65774465766963652e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e7072" .
            "6f746f22f5010a0f5172436f64654e6577446576696365121f0a07726571" .
            "7565737418012001280b320e2e70726f746f2e5265717565737412100a08" .
            "6170705f6e616d65180220012809120e0a066170705f696418032001280d" .
            "12190a116170705f6275696c645f76657273696f6e18042001280d12130a" .
            "0b6170705f76657273696f6e18052001280912210a08706c6174666f726d" .
            "18062001280e320f2e70726f746f2e506c6174666f726d12180a10706c61" .
            "74666f726d5f76657273696f6e180720012809121d0a0664657669636518" .
            "082001280e320d2e70726f746f2e44657669636512130a0b646576696365" .
            "5f6e616d6518092001280922680a175172436f64654e6577446576696365" .
            "526573706f6e736512210a08726573706f6e736518012001280b320f2e70" .
            "726f746f2e526573706f6e736512150a0d71725f636f64655f696d616765" .
            "18022001280c12130a0b6578706972655f74696d6518032001280d42260a" .
            "0e6e65742e694761702e70726f746f421450726f746f5172436f64654e65" .
            "77446576696365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

