<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QrCodeJoin.proto

namespace GPBMetadata;

class QrCodeJoin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9010a105172436f64654a6f696e2e70726f746f120570726f746f1a0e" .
            "526573706f6e73652e70726f746f22430a0a5172436f64654a6f696e121f" .
            "0a077265717565737418012001280b320e2e70726f746f2e526571756573" .
            "7412140a0c696e766974655f746f6b656e180220012809224e0a12517243" .
            "6f64654a6f696e526573706f6e736512210a08726573706f6e7365180120" .
            "01280b320f2e70726f746f2e526573706f6e736512150a0d71725f636f64" .
            "655f696d61676518022001280c42210a0e6e65742e694761702e70726f74" .
            "6f420f50726f746f5172436f64654a6f696e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

