<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a550a0d526571756573742e70726f746f120570726f746f22150a075265" .
            "7175657374120a0a026964180120012809421e0a0e6e65742e694761702e" .
            "70726f746f420c50726f746f52657175657374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

