<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingRate.proto

namespace GPBMetadata;

class SignalingRate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a135369676e616c696e67526174652e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f225a0a0d5369676e616c696e67" .
            "52617465121f0a077265717565737418012001280b320e2e70726f746f2e" .
            "52657175657374120a0a026964180220012804120c0a0472617465180320" .
            "01280d120e0a06726561736f6e180420012809223a0a155369676e616c69" .
            "6e6752617465526573706f6e736512210a08726573706f6e736518012001" .
            "280b320f2e70726f746f2e526573706f6e736542240a0e6e65742e694761" .
            "702e70726f746f421250726f746f5369676e616c696e6752617465620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

