<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingClearLog.proto

namespace GPBMetadata;

class SignalingClearLog
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc010a175369676e616c696e67436c6561724c6f672e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22460a115369676e61" .
            "6c696e67436c6561724c6f67121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e5265717565737412100a08636c6561725f6964180220" .
            "01280422500a195369676e616c696e67436c6561724c6f67526573706f6e" .
            "736512210a08726573706f6e736518012001280b320f2e70726f746f2e52" .
            "6573706f6e736512100a08636c6561725f696418022001280442280a0e6e" .
            "65742e694761702e70726f746f421650726f746f5369676e616c696e6743" .
            "6c6561724c6f67620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

