<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileCheckUsername.proto

namespace GPBMetadata;

class UserProfileCheckUsername
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8020a1e5573657250726f66696c65436865636b557365726e616d652e" .
            "70726f746f120570726f746f1a0e526573706f6e73652e70726f746f224d" .
            "0a185573657250726f66696c65436865636b557365726e616d65121f0a07" .
            "7265717565737418012001280b320e2e70726f746f2e5265717565737412" .
            "100a08757365726e616d6518022001280922b6010a205573657250726f66" .
            "696c65436865636b557365726e616d65526573706f6e736512210a087265" .
            "73706f6e736518012001280b320f2e70726f746f2e526573706f6e736512" .
            "3e0a0673746174757318022001280e322e2e70726f746f2e557365725072" .
            "6f66696c65436865636b557365726e616d65526573706f6e73652e537461" .
            "747573222f0a06537461747573120b0a07494e56414c4944100012090a05" .
            "54414b454e1001120d0a09415641494c41424c451002422f0a0e6e65742e" .
            "694761702e70726f746f421d50726f746f5573657250726f66696c654368" .
            "65636b557365726e616d65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

