<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetGender.proto

namespace GPBMetadata;

class UserProfileGetGender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a1a5573657250726f66696c6547657447656e6465722e70726f74" .
            "6f120570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62" .
            "616c2e70726f746f22370a145573657250726f66696c6547657447656e64" .
            "6572121f0a077265717565737418012001280b320e2e70726f746f2e5265" .
            "717565737422600a1c5573657250726f66696c6547657447656e64657252" .
            "6573706f6e736512210a08726573706f6e736518012001280b320f2e7072" .
            "6f746f2e526573706f6e7365121d0a0667656e64657218022001280e320d" .
            "2e70726f746f2e47656e646572422b0a0e6e65742e694761702e70726f74" .
            "6f421950726f746f5573657250726f66696c6547657447656e6465726206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

