<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsEdit.proto

namespace GPBMetadata;

class UserContactsEdit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3020a1655736572436f6e7461637473456469742e70726f746f120570" .
            "726f746f1a0e526573706f6e73652e70726f746f22690a1055736572436f" .
            "6e746163747345646974121f0a077265717565737418012001280b320e2e" .
            "70726f746f2e52657175657374120d0a0570686f6e651802200128041212" .
            "0a0a66697273745f6e616d6518032001280912110a096c6173745f6e616d" .
            "651804200128092285010a1855736572436f6e7461637473456469745265" .
            "73706f6e736512210a08726573706f6e736518012001280b320f2e70726f" .
            "746f2e526573706f6e7365120d0a0570686f6e6518022001280412120a0a" .
            "66697273745f6e616d6518032001280912110a096c6173745f6e616d6518" .
            "042001280912100a08696e697469616c7318052001280942270a0e6e6574" .
            "2e694761702e70726f746f421550726f746f55736572436f6e7461637473" .
            "45646974620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

