<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileSetSelfRemove.proto

namespace GPBMetadata;

class UserProfileSetSelfRemove
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9e020a1e5573657250726f66696c6553657453656c6652656d6f76652e" .
            "70726f746f120570726f746f1a0e526573706f6e73652e70726f746f2250" .
            "0a185573657250726f66696c6553657453656c6652656d6f7665121f0a07" .
            "7265717565737418012001280b320e2e70726f746f2e5265717565737412" .
            "130a0b73656c665f72656d6f766518022001280d225a0a20557365725072" .
            "6f66696c6553657453656c6652656d6f7665526573706f6e736512210a08" .
            "726573706f6e736518012001280b320f2e70726f746f2e526573706f6e73" .
            "6512130a0b73656c665f72656d6f766518022001280d422f0a0e6e65742e" .
            "694761702e70726f746f421d50726f746f5573657250726f66696c655365" .
            "7453656c6652656d6f7665620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

