<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserGetDeleteToken.proto

namespace GPBMetadata;

class UserGetDeleteToken
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab2020a185573657247657444656c657465546f6b656e2e70726f746f12" .
            "0570726f746f1a0e526573706f6e73652e70726f746f22350a1255736572" .
            "47657444656c657465546f6b656e121f0a07726571756573741801200128" .
            "0b320e2e70726f746f2e526571756573742294010a1a5573657247657444" .
            "656c657465546f6b656e526573706f6e736512210a08726573706f6e7365" .
            "18012001280b320f2e70726f746f2e526573706f6e736512140a0c726573" .
            "656e645f64656c617918022001280d12120a0a736d735f6e756d62657218" .
            "032003280412130a0b746f6b656e5f726567657818042001280912140a0c" .
            "746f6b656e5f6c656e67746818052001280942290a0e6e65742e69476170" .
            "2e70726f746f421750726f746f5573657247657444656c657465546f6b65" .
            "6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

