<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationCheckPassword.proto

namespace GPBMetadata;

class UserTwoStepVerificationCheckPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6020a2a5573657254776f53746570566572696669636174696f6e4368" .
            "65636b50617373776f72642e70726f746f120570726f746f1a0e52657370" .
            "6f6e73652e70726f746f22590a245573657254776f537465705665726966" .
            "69636174696f6e436865636b50617373776f7264121f0a07726571756573" .
            "7418012001280b320e2e70726f746f2e5265717565737412100a08706173" .
            "73776f726418022001280922510a2c5573657254776f5374657056657269" .
            "6669636174696f6e436865636b50617373776f7264526573706f6e736512" .
            "210a08726573706f6e736518012001280b320f2e70726f746f2e52657370" .
            "6f6e7365423b0a0e6e65742e694761702e70726f746f422950726f746f55" .
            "73657254776f53746570566572696669636174696f6e436865636b506173" .
            "73776f7264620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

