<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationRecoverPasswordByToken.proto

namespace GPBMetadata;

class UserTwoStepVerificationRecoverPasswordByToken
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6020a335573657254776f53746570566572696669636174696f6e5265" .
            "636f76657250617373776f72644279546f6b656e2e70726f746f12057072" .
            "6f746f1a0e526573706f6e73652e70726f746f225f0a2d5573657254776f" .
            "53746570566572696669636174696f6e5265636f76657250617373776f72" .
            "644279546f6b656e121f0a077265717565737418012001280b320e2e7072" .
            "6f746f2e52657175657374120d0a05746f6b656e18022001280922690a35" .
            "5573657254776f53746570566572696669636174696f6e5265636f766572" .
            "50617373776f72644279546f6b656e526573706f6e736512210a08726573" .
            "706f6e736518012001280b320f2e70726f746f2e526573706f6e7365120d" .
            "0a05746f6b656e18022001280942440a0e6e65742e694761702e70726f74" .
            "6f423250726f746f5573657254776f53746570566572696669636174696f" .
            "6e5265636f76657250617373776f72644279546f6b656e620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

