<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsGetBlockedList.proto

namespace GPBMetadata;

class UserContactsGetBlockedList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae6020a2055736572436f6e7461637473476574426c6f636b65644c6973" .
            "742e70726f746f120570726f746f1a0e526573706f6e73652e70726f746f" .
            "223d0a1a55736572436f6e7461637473476574426c6f636b65644c697374" .
            "121f0a077265717565737418012001280b320e2e70726f746f2e52657175" .
            "65737422b0010a2255736572436f6e7461637473476574426c6f636b6564" .
            "4c697374526573706f6e736512210a08726573706f6e736518012001280b" .
            "320f2e70726f746f2e526573706f6e7365123c0a04757365721802200328" .
            "0b322e2e70726f746f2e55736572436f6e7461637473476574426c6f636b" .
            "65644c697374526573706f6e73652e557365721a290a0455736572120f0a" .
            "07757365725f696418012001280412100a0863616368655f696418022001" .
            "280942310a0e6e65742e694761702e70726f746f421f50726f746f557365" .
            "72436f6e7461637473476574426c6f636b65644c697374620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

