<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserUpdateStatus.proto

namespace GPBMetadata;

class UserUpdateStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9020a16557365725570646174655374617475732e70726f746f120570" .
            "726f746f1a0e526573706f6e73652e70726f746f2286010a105573657255" .
            "7064617465537461747573121f0a077265717565737418012001280b320e" .
            "2e70726f746f2e52657175657374122e0a0673746174757318022001280e" .
            "321e2e70726f746f2e557365725570646174655374617475732e53746174" .
            "757322210a06537461747573120a0a064f4e4c494e451000120b0a074f46" .
            "464c494e451001227e0a1855736572557064617465537461747573526573" .
            "706f6e736512210a08726573706f6e736518012001280b320f2e70726f74" .
            "6f2e526573706f6e7365122e0a0673746174757318022001280e321e2e70" .
            "726f746f2e557365725570646174655374617475732e537461747573120f" .
            "0a07757365725f696418082001280442270a0e6e65742e694761702e7072" .
            "6f746f421550726f746f5573657255706461746553746174757362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

