<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsUnblock.proto

namespace GPBMetadata;

class UserContactsUnblock
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a82020a1955736572436f6e7461637473556e626c6f636b2e70726f746f" .
            "120570726f746f1a0e526573706f6e73652e70726f746f22470a13557365" .
            "72436f6e7461637473556e626c6f636b121f0a0772657175657374180120" .
            "01280b320e2e70726f746f2e52657175657374120f0a07757365725f6964" .
            "18022001280422510a1b55736572436f6e7461637473556e626c6f636b52" .
            "6573706f6e736512210a08726573706f6e736518012001280b320f2e7072" .
            "6f746f2e526573706f6e7365120f0a07757365725f696418022001280442" .
            "2a0a0e6e65742e694761702e70726f746f421850726f746f55736572436f" .
            "6e7461637473556e626c6f636b620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

