<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserVerifyNewDevice.proto

namespace GPBMetadata;

class UserVerifyNewDevice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae0030a19557365725665726966794e65774465766963652e70726f746f" .
            "120570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f6261" .
            "6c2e70726f746f22450a13557365725665726966794e6577446576696365" .
            "121f0a077265717565737418012001280b320e2e70726f746f2e52657175" .
            "657374120d0a05746f6b656e18022001280922a2020a1b55736572566572" .
            "6966794e6577446576696365526573706f6e736512210a08726573706f6e" .
            "736518012001280b320f2e70726f746f2e526573706f6e736512100a0861" .
            "70705f6e616d65180220012809120e0a066170705f696418032001280d12" .
            "190a116170705f6275696c645f76657273696f6e18042001280d12130a0b" .
            "6170705f76657273696f6e18052001280912210a08706c6174666f726d18" .
            "062001280e320f2e70726f746f2e506c6174666f726d12180a10706c6174" .
            "666f726d5f76657273696f6e180720012809121d0a066465766963651808" .
            "2001280e320d2e70726f746f2e44657669636512130a0b6465766963655f" .
            "6e616d65180920012809121d0a1574776f5f737465705f76657269666963" .
            "6174696f6e180a20012808422a0a0e6e65742e694761702e70726f746f42" .
            "1850726f746f557365725665726966794e6577446576696365620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

