<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAvatarAdd.proto

namespace GPBMetadata;

class UserAvatarAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\PBGlobal::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89020a13557365724176617461724164642e70726f746f120570726f74" .
            "6f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c2e70726f74" .
            "6f22440a0d55736572417661746172416464121f0a077265717565737418" .
            "012001280b320e2e70726f746f2e5265717565737412120a0a6174746163" .
            "686d656e7418022001280922590a15557365724176617461724164645265" .
            "73706f6e736512210a08726573706f6e736518012001280b320f2e70726f" .
            "746f2e526573706f6e7365121d0a0661766174617218022001280b320d2e" .
            "70726f746f2e41766174617242240a0e6e65742e694761702e70726f746f" .
            "421250726f746f55736572417661746172416464620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

