<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetBio.proto

namespace GPBMetadata;

class UserProfileGetBio
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5010a175573657250726f66696c6547657442696f2e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22340a115573657250" .
            "726f66696c6547657442696f121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e52657175657374224b0a195573657250726f66696c65" .
            "47657442696f526573706f6e736512210a08726573706f6e736518012001" .
            "280b320f2e70726f746f2e526573706f6e7365120b0a0362696f18022001" .
            "280942280a0e6e65742e694761702e70726f746f421650726f746f557365" .
            "7250726f66696c6547657442696f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

