<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationResendVerifyEmail.proto

namespace GPBMetadata;

class UserTwoStepVerificationResendVerifyEmail
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7020a2e5573657254776f53746570566572696669636174696f6e5265" .
            "73656e64566572696679456d61696c2e70726f746f120570726f746f1a0e" .
            "526573706f6e73652e70726f746f224b0a285573657254776f5374657056" .
            "6572696669636174696f6e526573656e64566572696679456d61696c121f" .
            "0a077265717565737418012001280b320e2e70726f746f2e526571756573" .
            "7422780a305573657254776f53746570566572696669636174696f6e5265" .
            "73656e64566572696679456d61696c526573706f6e736512210a08726573" .
            "706f6e736518012001280b320f2e70726f746f2e526573706f6e73651221" .
            "0a19756e636f6e6669726d65645f656d61696c5f7061747465726e180220" .
            "012809423f0a0e6e65742e694761702e70726f746f422d50726f746f5573" .
            "657254776f53746570566572696669636174696f6e526573656e64566572" .
            "696679456d61696c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

