<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsBlock.proto

namespace GPBMetadata;

class UserContactsBlock
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afa010a1755736572436f6e7461637473426c6f636b2e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f22450a115573657243" .
            "6f6e7461637473426c6f636b121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e52657175657374120f0a07757365725f696418022001" .
            "2804224f0a1955736572436f6e7461637473426c6f636b526573706f6e73" .
            "6512210a08726573706f6e736518012001280b320f2e70726f746f2e5265" .
            "73706f6e7365120f0a07757365725f696418022001280442280a0e6e6574" .
            "2e694761702e70726f746f421650726f746f55736572436f6e7461637473" .
            "426c6f636b620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

