<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationRecoverPasswordByAnswers.proto

namespace GPBMetadata;

class UserTwoStepVerificationRecoverPasswordByAnswers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87030a355573657254776f53746570566572696669636174696f6e5265" .
            "636f76657250617373776f72644279416e73776572732e70726f746f1205" .
            "70726f746f1a0e526573706f6e73652e70726f746f227a0a2f5573657254" .
            "776f53746570566572696669636174696f6e5265636f7665725061737377" .
            "6f72644279416e7377657273121f0a077265717565737418012001280b32" .
            "0e2e70726f746f2e5265717565737412120a0a616e737765725f6f6e6518" .
            "022001280912120a0a616e737765725f74776f180320012809226b0a3755" .
            "73657254776f53746570566572696669636174696f6e5265636f76657250" .
            "617373776f72644279416e7377657273526573706f6e736512210a087265" .
            "73706f6e736518012001280b320f2e70726f746f2e526573706f6e736512" .
            "0d0a05746f6b656e18022001280942460a0e6e65742e694761702e70726f" .
            "746f423450726f746f5573657254776f5374657056657269666963617469" .
            "6f6e5265636f76657250617373776f72644279416e737765727362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

