<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserPrivacySetRule.proto

namespace GPBMetadata;

class UserPrivacySetRule
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Request::initOnce();
        \GPBMetadata\Response::initOnce();
        \GPBMetadata\Global::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af7020a18557365725072697661637953657452756c652e70726f746f12" .
            "0570726f746f1a0e526573706f6e73652e70726f746f1a0c476c6f62616c" .
            "2e70726f746f227b0a12557365725072697661637953657452756c65121f" .
            "0a077265717565737418012001280b320e2e70726f746f2e526571756573" .
            "7412200a047479706518022001280e32122e70726f746f2e507269766163" .
            "795479706512220a056c6576656c18032001280e32132e70726f746f2e50" .
            "7269766163794c6576656c2285010a1a5573657250726976616379536574" .
            "52756c65526573706f6e736512210a08726573706f6e736518012001280b" .
            "320f2e70726f746f2e526573706f6e736512200a04747970651802200128" .
            "0e32122e70726f746f2e507269766163795479706512220a056c6576656c" .
            "18032001280e32132e70726f746f2e507269766163794c6576656c42290a" .
            "0e6e65742e694761702e70726f746f421750726f746f5573657250726976" .
            "61637953657452756c65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

