<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserSessionGetActiveList.proto

namespace Proto\UserSessionGetActiveListResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserSessionGetActiveListResponse.Session</code>
 */
class Session extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 session_id = 1;</code>
     */
    private $session_id = 0;
    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     */
    private $app_name = '';
    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     */
    private $app_id = 0;
    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     */
    private $app_build_version = 0;
    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     */
    private $app_version = '';
    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     */
    private $platform = 0;
    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     */
    private $platform_version = '';
    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     */
    private $device = 0;
    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     */
    private $device_name = '';
    /**
     * Generated from protobuf field <code>.proto.Language language = 10;</code>
     */
    private $language = 0;
    /**
     * Generated from protobuf field <code>string country = 11;</code>
     */
    private $country = '';
    /**
     * Generated from protobuf field <code>bool current = 12;</code>
     */
    private $current = false;
    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     */
    private $create_time = 0;
    /**
     * Generated from protobuf field <code>uint32 active_time = 14;</code>
     */
    private $active_time = 0;
    /**
     * Generated from protobuf field <code>string ip = 15;</code>
     */
    private $ip = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $session_id
     *     @type string $app_name
     *     @type int $app_id
     *     @type int $app_build_version
     *     @type string $app_version
     *     @type int $platform
     *     @type string $platform_version
     *     @type int $device
     *     @type string $device_name
     *     @type int $language
     *     @type string $country
     *     @type bool $current
     *     @type int $create_time
     *     @type int $active_time
     *     @type string $ip
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserSessionGetActiveList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 session_id = 1;</code>
     * @return int|string
     */
    public function getSessionId()
    {
        return $this->session_id;
    }

    /**
     * Generated from protobuf field <code>uint64 session_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     * @return int
     */
    public function getAppBuildVersion()
    {
        return $this->app_build_version;
    }

    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAppBuildVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_build_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return $this->app_version;
    }

    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkEnum($var, \Proto\Platform::class);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     * @return string
     */
    public function getPlatformVersion()
    {
        return $this->platform_version;
    }

    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     * @return int
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkEnum($var, \Proto\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Language language = 10;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>.proto.Language language = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \Proto\Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 11;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool current = 12;</code>
     * @return bool
     */
    public function getCurrent()
    {
        return $this->current;
    }

    /**
     * Generated from protobuf field <code>bool current = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setCurrent($var)
    {
        GPBUtil::checkBool($var);
        $this->current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     * @return int
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 active_time = 14;</code>
     * @return int
     */
    public function getActiveTime()
    {
        return $this->active_time;
    }

    /**
     * Generated from protobuf field <code>uint32 active_time = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setActiveTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->active_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 15;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Session::class, \Proto\UserSessionGetActiveListResponse_Session::class);

