<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetMessagesStats.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ChannelGetMessagesStatsResponse\Stats instead.
     * @deprecated
     */
    class ChannelGetMessagesStatsResponse_Stats {}
}
class_exists(ChannelGetMessagesStatsResponse\Stats::class);
@trigger_error('Proto\ChannelGetMessagesStatsResponse_Stats is deprecated and will be removed in the next major release. Use Proto\ChannelGetMessagesStatsResponse\Stats instead', E_USER_DEPRECATED);

