<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetMessagesStats.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelGetMessagesStatsResponse</code>
 */
class ChannelGetMessagesStatsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMessagesStatsResponse.Stats stats = 2;</code>
     */
    private $stats;

    public function __construct() {
        \GPBMetadata\ChannelGetMessagesStats::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMessagesStatsResponse.Stats stats = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStats()
    {
        return $this->stats;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMessagesStatsResponse.Stats stats = 2;</code>
     * @param \Proto\ChannelGetMessagesStatsResponse_Stats[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStats($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ChannelGetMessagesStatsResponse_Stats::class);
        $this->stats = $arr;

        return $this;
    }

}

