<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelPinMessage.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelPinMessageResponse</code>
 */
class ChannelPinMessageResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     */
    private $room_id = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage pinned_message = 3;</code>
     */
    private $pinned_message = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type int|string $room_id
     *     @type \Proto\RoomMessage $pinned_message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelPinMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage pinned_message = 3;</code>
     * @return \Proto\RoomMessage
     */
    public function getPinnedMessage()
    {
        return $this->pinned_message;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage pinned_message = 3;</code>
     * @param \Proto\RoomMessage $var
     * @return $this
     */
    public function setPinnedMessage($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage::class);
        $this->pinned_message = $var;

        return $this;
    }

}

