<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelAddMessageReaction.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelAddMessageReactionResponse</code>
 */
class ChannelAddMessageReactionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string reaction_counter_label = 2;</code>
     */
    private $reaction_counter_label = '';

    public function __construct() {
        \GPBMetadata\ChannelAddMessageReaction::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string reaction_counter_label = 2;</code>
     * @return string
     */
    public function getReactionCounterLabel()
    {
        return $this->reaction_counter_label;
    }

    /**
     * Generated from protobuf field <code>string reaction_counter_label = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReactionCounterLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->reaction_counter_label = $var;

        return $this;
    }

}

