<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetMemberList.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelGetMemberListResponse</code>
 */
class ChannelGetMemberListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMemberListResponse.Member member = 2;</code>
     */
    private $member;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\ChannelGetMemberListResponse\Member[]|\Google\Protobuf\Internal\RepeatedField $member
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ChannelGetMemberList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMemberListResponse.Member member = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMember()
    {
        return $this->member;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.ChannelGetMemberListResponse.Member member = 2;</code>
     * @param \Proto\ChannelGetMemberListResponse\Member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMember($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\ChannelGetMemberListResponse\Member::class);
        $this->member = $arr;

        return $this;
    }

}

