<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelUpdateReactionStatus.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChannelUpdateReactionStatus</code>
 */
class ChannelUpdateReactionStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     */
    private $room_id = 0;
    /**
     * Generated from protobuf field <code>bool reaction_status = 3;</code>
     */
    private $reaction_status = false;

    public function __construct() {
        \GPBMetadata\ChannelUpdateReactionStatus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @return int|string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>uint64 room_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool reaction_status = 3;</code>
     * @return bool
     */
    public function getReactionStatus()
    {
        return $this->reaction_status;
    }

    /**
     * Generated from protobuf field <code>bool reaction_status = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setReactionStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->reaction_status = $var;

        return $this;
    }

}

