<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ChannelRoom\PublicExtra instead.
     * @deprecated
     */
    class ChannelRoom_PublicExtra {}
}
class_exists(ChannelRoom\PublicExtra::class);
@trigger_error('Proto\ChannelRoom_PublicExtra is deprecated and will be removed in the next major release. Use Proto\ChannelRoom\PublicExtra instead', E_USER_DEPRECATED);

