<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChannelGetMemberList.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ChannelGetMemberList\FilterRole instead.
     * @deprecated
     */
    class ChannelGetMemberList_FilterRole {}
}
class_exists(ChannelGetMemberList\FilterRole::class);
@trigger_error('Proto\ChannelGetMemberList_FilterRole is deprecated and will be removed in the next major release. Use Proto\ChannelGetMemberList\FilterRole instead', E_USER_DEPRECATED);

