<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ChatRoom</code>
 */
class ChatRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     */
    private $peer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\RegisteredUser $peer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     * @return \Proto\RegisteredUser
     */
    public function getPeer()
    {
        return $this->peer;
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 1;</code>
     * @param \Proto\RegisteredUser $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkMessage($var, \Proto\RegisteredUser::class);
        $this->peer = $var;

        return $this;
    }

}

