<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientSearchRoomHistory.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\ClientSearchRoomHistory\Filter</code>
 */
class ClientSearchRoomHistory_Filter
{
    /**
     * Generated from protobuf enum <code>IMAGE = 0;</code>
     */
    const IMAGE = 0;
    /**
     * Generated from protobuf enum <code>VIDEO = 1;</code>
     */
    const VIDEO = 1;
    /**
     * Generated from protobuf enum <code>AUDIO = 2;</code>
     */
    const AUDIO = 2;
    /**
     * Generated from protobuf enum <code>VOICE = 3;</code>
     */
    const VOICE = 3;
    /**
     * Generated from protobuf enum <code>GIF = 4;</code>
     */
    const GIF = 4;
    /**
     * Generated from protobuf enum <code>FILE = 5;</code>
     */
    const FILE = 5;
    /**
     * Generated from protobuf enum <code>URL = 6;</code>
     */
    const URL = 6;
}

