<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientResolveUsername.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClientResolveUsernameResponse\Type instead.
     * @deprecated
     */
    class ClientResolveUsernameResponse_Type {}
}
class_exists(ClientResolveUsernameResponse\Type::class);
@trigger_error('Proto\ClientResolveUsernameResponse_Type is deprecated and will be removed in the next major release. Use Proto\ClientResolveUsernameResponse\Type instead', E_USER_DEPRECATED);

