<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\ClientAction</code>
 */
class ClientAction
{
    /**
     * Generated from protobuf enum <code>CANCEL = 0;</code>
     */
    const CANCEL = 0;
    /**
     * Generated from protobuf enum <code>TYPING = 1;</code>
     */
    const TYPING = 1;
    /**
     * Generated from protobuf enum <code>SENDING_IMAGE = 2;</code>
     */
    const SENDING_IMAGE = 2;
    /**
     * Generated from protobuf enum <code>CAPTURING_IMAGE = 3;</code>
     */
    const CAPTURING_IMAGE = 3;
    /**
     * Generated from protobuf enum <code>SENDING_VIDEO = 4;</code>
     */
    const SENDING_VIDEO = 4;
    /**
     * Generated from protobuf enum <code>CAPTURING_VIDEO = 5;</code>
     */
    const CAPTURING_VIDEO = 5;
    /**
     * Generated from protobuf enum <code>SENDING_AUDIO = 6;</code>
     */
    const SENDING_AUDIO = 6;
    /**
     * Generated from protobuf enum <code>RECORDING_VOICE = 7;</code>
     */
    const RECORDING_VOICE = 7;
    /**
     * Generated from protobuf enum <code>SENDING_VOICE = 8;</code>
     */
    const SENDING_VOICE = 8;
    /**
     * Generated from protobuf enum <code>SENDING_DOCUMENT = 9;</code>
     */
    const SENDING_DOCUMENT = 9;
    /**
     * Generated from protobuf enum <code>SENDING_GIF = 10;</code>
     */
    const SENDING_GIF = 10;
    /**
     * Generated from protobuf enum <code>SENDING_FILE = 11;</code>
     */
    const SENDING_FILE = 11;
    /**
     * Generated from protobuf enum <code>SENDING_LOCATION = 12;</code>
     */
    const SENDING_LOCATION = 12;
    /**
     * Generated from protobuf enum <code>CHOOSING_CONTACT = 13;</code>
     */
    const CHOOSING_CONTACT = 13;
    /**
     * Generated from protobuf enum <code>PAINTING = 14;</code>
     */
    const PAINTING = 14;
}

