<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientGetRoomHistory.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClientGetRoomHistory\Direction instead.
     * @deprecated
     */
    class ClientGetRoomHistory_Direction {}
}
class_exists(ClientGetRoomHistory\Direction::class);
@trigger_error('Proto\ClientGetRoomHistory_Direction is deprecated and will be removed in the next major release. Use Proto\ClientGetRoomHistory\Direction instead', E_USER_DEPRECATED);

