<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientResolveUsername.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\ClientResolveUsernameResponse\Type</code>
 */
class ClientResolveUsernameResponse_Type
{
    /**
     * Generated from protobuf enum <code>USER = 0;</code>
     */
    const USER = 0;
    /**
     * Generated from protobuf enum <code>ROOM = 1;</code>
     */
    const ROOM = 1;
}

