<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientCondition.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\ClientCondition\Room\OfflineMute</code>
 */
class ClientCondition_Room_OfflineMute
{
    /**
     * Generated from protobuf enum <code>UNCHANGED = 0;</code>
     */
    const UNCHANGED = 0;
    /**
     * Generated from protobuf enum <code>MUTED = 1;</code>
     */
    const MUTED = 1;
    /**
     * Generated from protobuf enum <code>UNMUTED = 2;</code>
     */
    const UNMUTED = 2;
}

