<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientCondition.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClientCondition\Room\OfflineDeleted instead.
     * @deprecated
     */
    class ClientCondition_Room_OfflineDeleted {}
}
class_exists(ClientCondition\Room\OfflineDeleted::class);
@trigger_error('Proto\ClientCondition_Room_OfflineDeleted is deprecated and will be removed in the next major release. Use Proto\ClientCondition\Room\OfflineDeleted instead', E_USER_DEPRECATED);

