<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientRoomReport.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClientRoomReport\Reason instead.
     * @deprecated
     */
    class ClientRoomReport_Reason {}
}
class_exists(ClientRoomReport\Reason::class);
@trigger_error('Proto\ClientRoomReport_Reason is deprecated and will be removed in the next major release. Use Proto\ClientRoomReport\Reason instead', E_USER_DEPRECATED);

