<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientCondition.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\ClientCondition\Room\OfflineEdited instead.
     * @deprecated
     */
    class ClientCondition_Room_OfflineEdited {}
}
class_exists(ClientCondition\Room\OfflineEdited::class);
@trigger_error('Proto\ClientCondition_Room_OfflineEdited is deprecated and will be removed in the next major release. Use Proto\ClientCondition\Room\OfflineEdited instead', E_USER_DEPRECATED);

