<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConnectionSecuring.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\ConnectionSymmetricKeyResponse\Status</code>
 */
class ConnectionSymmetricKeyResponse_Status
{
    /**
     * Generated from protobuf enum <code>REJECTED = 0;</code>
     */
    const REJECTED = 0;
    /**
     * Generated from protobuf enum <code>ACCEPTED = 1;</code>
     */
    const ACCEPTED = 1;
}

