<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConnectionSecuring.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.ConnectionSecuringResponse</code>
 */
class ConnectionSecuringResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string public_key = 2;</code>
     */
    private $public_key = '';
    /**
     * Generated from protobuf field <code>uint32 symmetric_key_length = 3;</code>
     */
    private $symmetric_key_length = 0;
    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval = 4;</code>
     */
    private $heartbeat_interval = 0;
    /**
     * Generated from protobuf field <code>string primary_node_name = 5;</code>
     */
    private $primary_node_name = '';
    /**
     * Generated from protobuf field <code>uint32 secondary_chunk_size = 6;</code>
     */
    private $secondary_chunk_size = 0;

    public function __construct() {
        \GPBMetadata\ConnectionSecuring::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key = 2;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 symmetric_key_length = 3;</code>
     * @return int
     */
    public function getSymmetricKeyLength()
    {
        return $this->symmetric_key_length;
    }

    /**
     * Generated from protobuf field <code>uint32 symmetric_key_length = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSymmetricKeyLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->symmetric_key_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval = 4;</code>
     * @return int
     */
    public function getHeartbeatInterval()
    {
        return $this->heartbeat_interval;
    }

    /**
     * Generated from protobuf field <code>uint32 heartbeat_interval = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartbeatInterval($var)
    {
        GPBUtil::checkUint32($var);
        $this->heartbeat_interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string primary_node_name = 5;</code>
     * @return string
     */
    public function getPrimaryNodeName()
    {
        return $this->primary_node_name;
    }

    /**
     * Generated from protobuf field <code>string primary_node_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryNodeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->primary_node_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 secondary_chunk_size = 6;</code>
     * @return int
     */
    public function getSecondaryChunkSize()
    {
        return $this->secondary_chunk_size;
    }

    /**
     * Generated from protobuf field <code>uint32 secondary_chunk_size = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSecondaryChunkSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->secondary_chunk_size = $var;

        return $this;
    }

}

