<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\Device</code>
 */
class Device
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_DEVICE = 0;</code>
     */
    const UNKNOWN_DEVICE = 0;
    /**
     * Generated from protobuf enum <code>PC = 1;</code>
     */
    const PC = 1;
    /**
     * Generated from protobuf enum <code>TABLET = 2;</code>
     */
    const TABLET = 2;
    /**
     * Generated from protobuf enum <code>MOBILE = 3;</code>
     */
    const MOBILE = 3;
}

