<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileDownload.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\FileDownload\Selector instead.
     * @deprecated
     */
    class FileDownload_Selector {}
}
class_exists(FileDownload\Selector::class);
@trigger_error('Proto\FileDownload_Selector is deprecated and will be removed in the next major release. Use Proto\FileDownload\Selector instead', E_USER_DEPRECATED);

