<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\GroupRoom\Type</code>
 */
class GroupRoom_Type
{
    /**
     * Generated from protobuf enum <code>PRIVATE_ROOM = 0;</code>
     */
    const PRIVATE_ROOM = 0;
    /**
     * Generated from protobuf enum <code>PUBLIC_ROOM = 1;</code>
     */
    const PUBLIC_ROOM = 1;
}

