<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupAddMember.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GroupAddMember\Member instead.
     * @deprecated
     */
    class GroupAddMember_Member {}
}
class_exists(GroupAddMember\Member::class);
@trigger_error('Proto\GroupAddMember_Member is deprecated and will be removed in the next major release. Use Proto\GroupAddMember\Member instead', E_USER_DEPRECATED);

