<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupCheckUsername.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GroupCheckUsernameResponse\Status instead.
     * @deprecated
     */
    class GroupCheckUsernameResponse_Status {}
}
class_exists(GroupCheckUsernameResponse\Status::class);
@trigger_error('Proto\GroupCheckUsernameResponse_Status is deprecated and will be removed in the next major release. Use Proto\GroupCheckUsernameResponse\Status instead', E_USER_DEPRECATED);

