<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GroupRoom</code>
 */
class GroupRoom extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Role role = 2;</code>
     */
    private $role = 0;
    /**
     * Generated from protobuf field <code>uint32 participants_count = 3;</code>
     */
    private $participants_count = 0;
    /**
     * Generated from protobuf field <code>string participants_count_label = 4;</code>
     */
    private $participants_count_label = '';
    /**
     * Generated from protobuf field <code>uint32 participants_count_limit = 5;</code>
     */
    private $participants_count_limit = 0;
    /**
     * Generated from protobuf field <code>string participants_count_limit_label = 6;</code>
     */
    private $participants_count_limit_label = '';
    /**
     * Generated from protobuf field <code>string description = 7;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>uint32 avatar_count = 8;</code>
     */
    private $avatar_count = 0;
    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 9;</code>
     */
    private $avatar = null;
    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PrivateExtra private_extra = 10;</code>
     */
    private $private_extra = null;
    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PublicExtra public_extra = 11;</code>
     */
    private $public_extra = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type int $role
     *     @type int $participants_count
     *     @type string $participants_count_label
     *     @type int $participants_count_limit
     *     @type string $participants_count_limit_label
     *     @type string $description
     *     @type int $avatar_count
     *     @type \Proto\Avatar $avatar
     *     @type \Proto\GroupRoom\PrivateExtra $private_extra
     *     @type \Proto\GroupRoom\PublicExtra $public_extra
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Proto\GroupRoom_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Role role = 2;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.Role role = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Proto\GroupRoom_Role::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 participants_count = 3;</code>
     * @return int
     */
    public function getParticipantsCount()
    {
        return $this->participants_count;
    }

    /**
     * Generated from protobuf field <code>uint32 participants_count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setParticipantsCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->participants_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string participants_count_label = 4;</code>
     * @return string
     */
    public function getParticipantsCountLabel()
    {
        return $this->participants_count_label;
    }

    /**
     * Generated from protobuf field <code>string participants_count_label = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantsCountLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->participants_count_label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 participants_count_limit = 5;</code>
     * @return int
     */
    public function getParticipantsCountLimit()
    {
        return $this->participants_count_limit;
    }

    /**
     * Generated from protobuf field <code>uint32 participants_count_limit = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setParticipantsCountLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->participants_count_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string participants_count_limit_label = 6;</code>
     * @return string
     */
    public function getParticipantsCountLimitLabel()
    {
        return $this->participants_count_limit_label;
    }

    /**
     * Generated from protobuf field <code>string participants_count_limit_label = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setParticipantsCountLimitLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->participants_count_limit_label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_count = 8;</code>
     * @return int
     */
    public function getAvatarCount()
    {
        return $this->avatar_count;
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_count = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setAvatarCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->avatar_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 9;</code>
     * @return \Proto\Avatar
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 9;</code>
     * @param \Proto\Avatar $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkMessage($var, \Proto\Avatar::class);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PrivateExtra private_extra = 10;</code>
     * @return \Proto\GroupRoom\PrivateExtra
     */
    public function getPrivateExtra()
    {
        return $this->private_extra;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PrivateExtra private_extra = 10;</code>
     * @param \Proto\GroupRoom\PrivateExtra $var
     * @return $this
     */
    public function setPrivateExtra($var)
    {
        GPBUtil::checkMessage($var, \Proto\GroupRoom_PrivateExtra::class);
        $this->private_extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PublicExtra public_extra = 11;</code>
     * @return \Proto\GroupRoom\PublicExtra
     */
    public function getPublicExtra()
    {
        return $this->public_extra;
    }

    /**
     * Generated from protobuf field <code>.proto.GroupRoom.PublicExtra public_extra = 11;</code>
     * @param \Proto\GroupRoom\PublicExtra $var
     * @return $this
     */
    public function setPublicExtra($var)
    {
        GPBUtil::checkMessage($var, \Proto\GroupRoom_PublicExtra::class);
        $this->public_extra = $var;

        return $this;
    }

}

