<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupCheckUsername.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\GroupCheckUsernameResponse\Status</code>
 */
class GroupCheckUsernameResponse_Status
{
    /**
     * Generated from protobuf enum <code>INVALID = 0;</code>
     */
    const INVALID = 0;
    /**
     * Generated from protobuf enum <code>TAKEN = 1;</code>
     */
    const TAKEN = 1;
    /**
     * Generated from protobuf enum <code>AVAILABLE = 2;</code>
     */
    const AVAILABLE = 2;
    /**
     * Generated from protobuf enum <code>OCCUPYING_LIMIT_EXCEEDED = 3;</code>
     */
    const OCCUPYING_LIMIT_EXCEEDED = 3;
}

