<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GroupRoom\Type instead.
     * @deprecated
     */
    class GroupRoom_Type {}
}
class_exists(GroupRoom\Type::class);
@trigger_error('Proto\GroupRoom_Type is deprecated and will be removed in the next major release. Use Proto\GroupRoom\Type instead', E_USER_DEPRECATED);

