<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupGetMemberList.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GroupGetMemberList\FilterRole instead.
     * @deprecated
     */
    class GroupGetMemberList_FilterRole {}
}
class_exists(GroupGetMemberList\FilterRole::class);
@trigger_error('Proto\GroupGetMemberList_FilterRole is deprecated and will be removed in the next major release. Use Proto\GroupGetMemberList\FilterRole instead', E_USER_DEPRECATED);

