<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GroupRoom\Role instead.
     * @deprecated
     */
    class GroupRoom_Role {}
}
class_exists(GroupRoom\Role::class);
@trigger_error('Proto\GroupRoom_Role is deprecated and will be removed in the next major release. Use Proto\GroupRoom\Role instead', E_USER_DEPRECATED);

