<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupGetDraft.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GroupGetDraftResponse</code>
 */
class GroupGetDraftResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>.proto.RoomDraft draft = 2;</code>
     */
    private $draft = null;

    public function __construct() {
        \GPBMetadata\GroupGetDraft::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomDraft draft = 2;</code>
     * @return \Proto\RoomDraft
     */
    public function getDraft()
    {
        return $this->draft;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomDraft draft = 2;</code>
     * @param \Proto\RoomDraft $var
     * @return $this
     */
    public function setDraft($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomDraft::class);
        $this->draft = $var;

        return $this;
    }

}

