<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoLocation.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.InfoLocationResponse</code>
 */
class InfoLocationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string iso_code = 2;</code>
     */
    private $iso_code = '';
    /**
     * Generated from protobuf field <code>uint32 calling_code = 3;</code>
     */
    private $calling_code = 0;
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string pattern = 5;</code>
     */
    private $pattern = '';
    /**
     * Generated from protobuf field <code>string regex = 6;</code>
     */
    private $regex = '';

    public function __construct() {
        \GPBMetadata\InfoLocation::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string iso_code = 2;</code>
     * @return string
     */
    public function getIsoCode()
    {
        return $this->iso_code;
    }

    /**
     * Generated from protobuf field <code>string iso_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIsoCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->iso_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 calling_code = 3;</code>
     * @return int
     */
    public function getCallingCode()
    {
        return $this->calling_code;
    }

    /**
     * Generated from protobuf field <code>uint32 calling_code = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCallingCode($var)
    {
        GPBUtil::checkUint32($var);
        $this->calling_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pattern = 5;</code>
     * @return string
     */
    public function getPattern()
    {
        return $this->pattern;
    }

    /**
     * Generated from protobuf field <code>string pattern = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->pattern = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string regex = 6;</code>
     * @return string
     */
    public function getRegex()
    {
        return $this->regex;
    }

    /**
     * Generated from protobuf field <code>string regex = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRegex($var)
    {
        GPBUtil::checkString($var, True);
        $this->regex = $var;

        return $this;
    }

}

