<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoWallpaper.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\InfoWallpaper\Fit</code>
 */
class InfoWallpaper_Fit
{
    /**
     * Generated from protobuf enum <code>PHONE = 0;</code>
     */
    const PHONE = 0;
    /**
     * Generated from protobuf enum <code>TABLET = 1;</code>
     */
    const TABLET = 1;
    /**
     * Generated from protobuf enum <code>DESKTOP = 2;</code>
     */
    const DESKTOP = 2;
}

