<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InfoWallpaper.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.InfoWallpaperResponse</code>
 */
class InfoWallpaperResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.Wallpaper wallpaper = 2;</code>
     */
    private $wallpaper;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\Wallpaper[]|\Google\Protobuf\Internal\RepeatedField $wallpaper
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\InfoWallpaper::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Wallpaper wallpaper = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWallpaper()
    {
        return $this->wallpaper;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Wallpaper wallpaper = 2;</code>
     * @param \Proto\Wallpaper[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWallpaper($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Wallpaper::class);
        $this->wallpaper = $arr;

        return $this;
    }

}

