<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\Platform</code>
 */
class Platform
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_PLATFORM = 0;</code>
     */
    const UNKNOWN_PLATFORM = 0;
    /**
     * Generated from protobuf enum <code>ANDROID = 1;</code>
     */
    const ANDROID = 1;
    /**
     * Generated from protobuf enum <code>IOS = 2;</code>
     */
    const IOS = 2;
    /**
     * Generated from protobuf enum <code>MAC_OS = 3;</code>
     */
    const MAC_OS = 3;
    /**
     * Generated from protobuf enum <code>WINDOWS = 4;</code>
     */
    const WINDOWS = 4;
    /**
     * Generated from protobuf enum <code>LINUX = 5;</code>
     */
    const LINUX = 5;
    /**
     * Generated from protobuf enum <code>BLACK_BERRY = 6;</code>
     */
    const BLACK_BERRY = 6;
}

