<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\PrivacyLevel</code>
 */
class PrivacyLevel
{
    /**
     * Generated from protobuf enum <code>ALLOW_ALL = 0;</code>
     */
    const ALLOW_ALL = 0;
    /**
     * Generated from protobuf enum <code>DENY_ALL = 1;</code>
     */
    const DENY_ALL = 1;
    /**
     * Generated from protobuf enum <code>ALLOW_CONTACTS = 2;</code>
     */
    const ALLOW_CONTACTS = 2;
}

