<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\RegisteredUser\Status</code>
 */
class RegisteredUser_Status
{
    /**
     * Generated from protobuf enum <code>LONG_TIME_AGO = 0;</code>
     */
    const LONG_TIME_AGO = 0;
    /**
     * Generated from protobuf enum <code>LAST_MONTH = 1;</code>
     */
    const LAST_MONTH = 1;
    /**
     * Generated from protobuf enum <code>LAST_WEEK = 2;</code>
     */
    const LAST_WEEK = 2;
    /**
     * Generated from protobuf enum <code>ONLINE = 3;</code>
     */
    const ONLINE = 3;
    /**
     * Generated from protobuf enum <code>EXACTLY = 4;</code>
     */
    const EXACTLY = 4;
    /**
     * Generated from protobuf enum <code>RECENTLY = 5;</code>
     */
    const RECENTLY = 5;
    /**
     * Generated from protobuf enum <code>SUPPORT = 6;</code>
     */
    const SUPPORT = 6;
    /**
     * Generated from protobuf enum <code>SERVICE_NOTIFICATIONS = 7;</code>
     */
    const SERVICE_NOTIFICATIONS = 7;
}

