<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\RegisteredUser\Status instead.
     * @deprecated
     */
    class RegisteredUser_Status {}
}
class_exists(RegisteredUser\Status::class);
@trigger_error('Proto\RegisteredUser_Status is deprecated and will be removed in the next major release. Use Proto\RegisteredUser\Status instead', E_USER_DEPRECATED);

