<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RegisteredUser</code>
 */
class RegisteredUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>uint64 phone = 3;</code>
     */
    private $phone = 0;
    /**
     * Generated from protobuf field <code>string first_name = 4;</code>
     */
    private $first_name = '';
    /**
     * Generated from protobuf field <code>string last_name = 5;</code>
     */
    private $last_name = '';
    /**
     * Generated from protobuf field <code>string display_name = 6;</code>
     */
    private $display_name = '';
    /**
     * Generated from protobuf field <code>string initials = 7;</code>
     */
    private $initials = '';
    /**
     * Generated from protobuf field <code>string color = 8;</code>
     */
    private $color = '';
    /**
     * Generated from protobuf field <code>.proto.RegisteredUser.Status status = 9;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>uint32 last_seen = 10;</code>
     */
    private $last_seen = 0;
    /**
     * Generated from protobuf field <code>uint32 avatar_count = 11;</code>
     */
    private $avatar_count = 0;
    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 12;</code>
     */
    private $avatar = null;
    /**
     * Generated from protobuf field <code>bool mutual = 13;</code>
     */
    private $mutual = false;
    /**
     * Generated from protobuf field <code>bool deleted = 14;</code>
     */
    private $deleted = false;
    /**
     * Generated from protobuf field <code>string cache_id = 15;</code>
     */
    private $cache_id = '';
    /**
     * Generated from protobuf field <code>string bio = 16;</code>
     */
    private $bio = '';
    /**
     * Generated from protobuf field <code>bool verified = 17;</code>
     */
    private $verified = false;

    public function __construct() {
        \GPBMetadata\Global::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 phone = 3;</code>
     * @return int|string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>uint64 phone = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkUint64($var);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_name = 4;</code>
     * @return string
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * Generated from protobuf field <code>string first_name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->first_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_name = 5;</code>
     * @return string
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * Generated from protobuf field <code>string last_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 6;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string initials = 7;</code>
     * @return string
     */
    public function getInitials()
    {
        return $this->initials;
    }

    /**
     * Generated from protobuf field <code>string initials = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInitials($var)
    {
        GPBUtil::checkString($var, True);
        $this->initials = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string color = 8;</code>
     * @return string
     */
    public function getColor()
    {
        return $this->color;
    }

    /**
     * Generated from protobuf field <code>string color = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser.Status status = 9;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser.Status status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Proto\RegisteredUser_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_seen = 10;</code>
     * @return int
     */
    public function getLastSeen()
    {
        return $this->last_seen;
    }

    /**
     * Generated from protobuf field <code>uint32 last_seen = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLastSeen($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_seen = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_count = 11;</code>
     * @return int
     */
    public function getAvatarCount()
    {
        return $this->avatar_count;
    }

    /**
     * Generated from protobuf field <code>uint32 avatar_count = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setAvatarCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->avatar_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 12;</code>
     * @return \Proto\Avatar
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 12;</code>
     * @param \Proto\Avatar $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkMessage($var, \Proto\Avatar::class);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool mutual = 13;</code>
     * @return bool
     */
    public function getMutual()
    {
        return $this->mutual;
    }

    /**
     * Generated from protobuf field <code>bool mutual = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setMutual($var)
    {
        GPBUtil::checkBool($var);
        $this->mutual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 14;</code>
     * @return bool
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cache_id = 15;</code>
     * @return string
     */
    public function getCacheId()
    {
        return $this->cache_id;
    }

    /**
     * Generated from protobuf field <code>string cache_id = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setCacheId($var)
    {
        GPBUtil::checkString($var, True);
        $this->cache_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bio = 16;</code>
     * @return string
     */
    public function getBio()
    {
        return $this->bio;
    }

    /**
     * Generated from protobuf field <code>string bio = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setBio($var)
    {
        GPBUtil::checkString($var, True);
        $this->bio = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool verified = 17;</code>
     * @return bool
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * Generated from protobuf field <code>bool verified = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->verified = $var;

        return $this;
    }

}

