<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\RoomMessage\Author instead.
     * @deprecated
     */
    class RoomMessage_Author {}
}
class_exists(RoomMessage\Author::class);
@trigger_error('Proto\RoomMessage_Author is deprecated and will be removed in the next major release. Use Proto\RoomMessage\Author instead', E_USER_DEPRECATED);

