<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\RoomMessage\ExtraType instead.
     * @deprecated
     */
    class RoomMessage_ExtraType {}
}
class_exists(RoomMessage\ExtraType::class);
@trigger_error('Proto\RoomMessage_ExtraType is deprecated and will be removed in the next major release. Use Proto\RoomMessage\ExtraType instead', E_USER_DEPRECATED);

