<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\Room\Type instead.
     * @deprecated
     */
    class Room_Type {}
}
class_exists(Room\Type::class);
@trigger_error('Proto\Room_Type is deprecated and will be removed in the next major release. Use Proto\Room\Type instead', E_USER_DEPRECATED);

