<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RoomMessageLog</code>
 */
class RoomMessageLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.ExtraType extra_type = 2;</code>
     */
    private $extra_type = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.TargetUser target_user = 3;</code>
     */
    private $target_user = null;

    public function __construct() {
        \GPBMetadata\Global::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Proto\RoomMessageLog_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.ExtraType extra_type = 2;</code>
     * @return int
     */
    public function getExtraType()
    {
        return $this->extra_type;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.ExtraType extra_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setExtraType($var)
    {
        GPBUtil::checkEnum($var, \Proto\RoomMessageLog_ExtraType::class);
        $this->extra_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.TargetUser target_user = 3;</code>
     * @return \Proto\RoomMessageLog_TargetUser
     */
    public function getTargetUser()
    {
        return $this->target_user;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog.TargetUser target_user = 3;</code>
     * @param \Proto\RoomMessageLog_TargetUser $var
     * @return $this
     */
    public function setTargetUser($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessageLog_TargetUser::class);
        $this->target_user = $var;

        return $this;
    }

}

