<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.RoomMessage</code>
 */
class RoomMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     */
    private $message_id = 0;
    /**
     * Generated from protobuf field <code>uint64 message_version = 2;</code>
     */
    private $message_version = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageStatus status = 3;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>uint64 status_version = 4;</code>
     */
    private $status_version = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageType message_type = 5;</code>
     */
    private $message_type = 0;
    /**
     * Generated from protobuf field <code>string message = 6;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>.proto.File attachment = 7;</code>
     */
    private $attachment = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author author = 8;</code>
     */
    private $author = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageLocation location = 9;</code>
     */
    private $location = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog log = 10;</code>
     */
    private $log = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessageContact contact = 11;</code>
     */
    private $contact = null;
    /**
     * Generated from protobuf field <code>bool edited = 12;</code>
     */
    private $edited = false;
    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     */
    private $create_time = 0;
    /**
     * Generated from protobuf field <code>uint32 update_time = 14;</code>
     */
    private $update_time = 0;
    /**
     * Generated from protobuf field <code>bool deleted = 15;</code>
     */
    private $deleted = false;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage forward_from = 16;</code>
     */
    private $forward_from = null;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage reply_to = 17;</code>
     */
    private $reply_to = null;
    /**
     * Generated from protobuf field <code>uint64 previous_message_id = 18;</code>
     */
    private $previous_message_id = 0;
    /**
     * Generated from protobuf field <code>uint64 random_id = 21;</code>
     */
    private $random_id = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ExtraType extra_type = 19;</code>
     */
    private $extra_type = 0;
    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ChannelExtra channel_extra = 20;</code>
     */
    private $channel_extra = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $message_id
     *     @type int|string $message_version
     *     @type int $status
     *     @type int|string $status_version
     *     @type int $message_type
     *     @type string $message
     *     @type \Proto\File $attachment
     *     @type \Proto\RoomMessage\Author $author
     *     @type \Proto\RoomMessageLocation $location
     *     @type \Proto\RoomMessageLog $log
     *     @type \Proto\RoomMessageContact $contact
     *     @type bool $edited
     *     @type int $create_time
     *     @type int $update_time
     *     @type bool $deleted
     *     @type \Proto\RoomMessage $forward_from
     *     @type \Proto\RoomMessage $reply_to
     *     @type int|string $previous_message_id
     *     @type int|string $random_id
     *     @type int $extra_type
     *     @type \Proto\RoomMessage\ChannelExtra $channel_extra
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PBGlobal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     * @return int|string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * Generated from protobuf field <code>uint64 message_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 message_version = 2;</code>
     * @return int|string
     */
    public function getMessageVersion()
    {
        return $this->message_version;
    }

    /**
     * Generated from protobuf field <code>uint64 message_version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->message_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageStatus status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageStatus status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Proto\RoomMessageStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 status_version = 4;</code>
     * @return int|string
     */
    public function getStatusVersion()
    {
        return $this->status_version;
    }

    /**
     * Generated from protobuf field <code>uint64 status_version = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStatusVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->status_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageType message_type = 5;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->message_type;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageType message_type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Proto\RoomMessageType::class);
        $this->message_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 6;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.File attachment = 7;</code>
     * @return \Proto\File
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    /**
     * Generated from protobuf field <code>.proto.File attachment = 7;</code>
     * @param \Proto\File $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkMessage($var, \Proto\File::class);
        $this->attachment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author author = 8;</code>
     * @return \Proto\RoomMessage\Author
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.Author author = 8;</code>
     * @param \Proto\RoomMessage\Author $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage_Author::class);
        $this->author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLocation location = 9;</code>
     * @return \Proto\RoomMessageLocation
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLocation location = 9;</code>
     * @param \Proto\RoomMessageLocation $var
     * @return $this
     */
    public function setLocation($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessageLocation::class);
        $this->location = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog log = 10;</code>
     * @return \Proto\RoomMessageLog
     */
    public function getLog()
    {
        return $this->log;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageLog log = 10;</code>
     * @param \Proto\RoomMessageLog $var
     * @return $this
     */
    public function setLog($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessageLog::class);
        $this->log = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageContact contact = 11;</code>
     * @return \Proto\RoomMessageContact
     */
    public function getContact()
    {
        return $this->contact;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessageContact contact = 11;</code>
     * @param \Proto\RoomMessageContact $var
     * @return $this
     */
    public function setContact($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessageContact::class);
        $this->contact = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool edited = 12;</code>
     * @return bool
     */
    public function getEdited()
    {
        return $this->edited;
    }

    /**
     * Generated from protobuf field <code>bool edited = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setEdited($var)
    {
        GPBUtil::checkBool($var);
        $this->edited = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     * @return int
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Generated from protobuf field <code>uint32 create_time = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 update_time = 14;</code>
     * @return int
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Generated from protobuf field <code>uint32 update_time = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->update_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 15;</code>
     * @return bool
     */
    public function getDeleted()
    {
        return $this->deleted;
    }

    /**
     * Generated from protobuf field <code>bool deleted = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->deleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage forward_from = 16;</code>
     * @return \Proto\RoomMessage
     */
    public function getForwardFrom()
    {
        return $this->forward_from;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage forward_from = 16;</code>
     * @param \Proto\RoomMessage $var
     * @return $this
     */
    public function setForwardFrom($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage::class);
        $this->forward_from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage reply_to = 17;</code>
     * @return \Proto\RoomMessage
     */
    public function getReplyTo()
    {
        return $this->reply_to;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage reply_to = 17;</code>
     * @param \Proto\RoomMessage $var
     * @return $this
     */
    public function setReplyTo($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage::class);
        $this->reply_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 previous_message_id = 18;</code>
     * @return int|string
     */
    public function getPreviousMessageId()
    {
        return $this->previous_message_id;
    }

    /**
     * Generated from protobuf field <code>uint64 previous_message_id = 18;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreviousMessageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->previous_message_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 random_id = 21;</code>
     * @return int|string
     */
    public function getRandomId()
    {
        return $this->random_id;
    }

    /**
     * Generated from protobuf field <code>uint64 random_id = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRandomId($var)
    {
        GPBUtil::checkUint64($var);
        $this->random_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ExtraType extra_type = 19;</code>
     * @return int
     */
    public function getExtraType()
    {
        return $this->extra_type;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ExtraType extra_type = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setExtraType($var)
    {
        GPBUtil::checkEnum($var, \Proto\RoomMessage_ExtraType::class);
        $this->extra_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ChannelExtra channel_extra = 20;</code>
     * @return \Proto\RoomMessage\ChannelExtra
     */
    public function getChannelExtra()
    {
        return $this->channel_extra;
    }

    /**
     * Generated from protobuf field <code>.proto.RoomMessage.ChannelExtra channel_extra = 20;</code>
     * @param \Proto\RoomMessage\ChannelExtra $var
     * @return $this
     */
    public function setChannelExtra($var)
    {
        GPBUtil::checkMessage($var, \Proto\RoomMessage_ChannelExtra::class);
        $this->channel_extra = $var;

        return $this;
    }

}

