<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto;

/**
 * Protobuf type <code>proto.RoomMute</code>
 */
class RoomMute
{
    /**
     * Generated from protobuf enum <code>UNMUTE = 0;</code>
     */
    const UNMUTE = 0;
    /**
     * Generated from protobuf enum <code>MUTE = 1;</code>
     */
    const MUTE = 1;
}

