<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingAccept.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingAcceptResponse</code>
 */
class SignalingAcceptResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string called_sdp = 2;</code>
     */
    private $called_sdp = '';

    public function __construct() {
        \GPBMetadata\SignalingAccept::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string called_sdp = 2;</code>
     * @return string
     */
    public function getCalledSdp()
    {
        return $this->called_sdp;
    }

    /**
     * Generated from protobuf field <code>string called_sdp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCalledSdp($var)
    {
        GPBUtil::checkString($var, True);
        $this->called_sdp = $var;

        return $this;
    }

}

