<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingGetLog.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\SignalingGetLogResponse\SignalingLog\Status</code>
 */
class SignalingGetLogResponse_SignalingLog_Status
{
    /**
     * Generated from protobuf enum <code>MISSED = 0;</code>
     */
    const MISSED = 0;
    /**
     * Generated from protobuf enum <code>CANCELED = 1;</code>
     */
    const CANCELED = 1;
    /**
     * Generated from protobuf enum <code>INCOMING = 2;</code>
     */
    const INCOMING = 2;
    /**
     * Generated from protobuf enum <code>OUTGOING = 3;</code>
     */
    const OUTGOING = 3;
}

