<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingClearLog.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingClearLog</code>
 */
class SignalingClearLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     */
    private $clear_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type int|string $clear_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SignalingClearLog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     * @return int|string
     */
    public function getClearId()
    {
        return $this->clear_id;
    }

    /**
     * Generated from protobuf field <code>uint64 clear_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClearId($var)
    {
        GPBUtil::checkUint64($var);
        $this->clear_id = $var;

        return $this;
    }

}

