<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingGetLog.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\SignalingGetLogResponse\SignalingLog instead.
     * @deprecated
     */
    class SignalingGetLogResponse_SignalingLog {}
}
class_exists(SignalingGetLogResponse\SignalingLog::class);
@trigger_error('Proto\SignalingGetLogResponse_SignalingLog is deprecated and will be removed in the next major release. Use Proto\SignalingGetLogResponse\SignalingLog instead', E_USER_DEPRECATED);

