<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingCandidate.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingCandidateResponse</code>
 */
class SignalingCandidateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string peer_candidate = 2;</code>
     */
    private $peer_candidate = '';
    /**
     * Generated from protobuf field <code>string peer_sdp_m_id = 3;</code>
     */
    private $peer_sdp_m_id = '';
    /**
     * Generated from protobuf field <code>uint32 peer_sdp_m_line_index = 4;</code>
     */
    private $peer_sdp_m_line_index = 0;

    public function __construct() {
        \GPBMetadata\SignalingCandidate::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string peer_candidate = 2;</code>
     * @return string
     */
    public function getPeerCandidate()
    {
        return $this->peer_candidate;
    }

    /**
     * Generated from protobuf field <code>string peer_candidate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerCandidate($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_candidate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string peer_sdp_m_id = 3;</code>
     * @return string
     */
    public function getPeerSdpMId()
    {
        return $this->peer_sdp_m_id;
    }

    /**
     * Generated from protobuf field <code>string peer_sdp_m_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeerSdpMId($var)
    {
        GPBUtil::checkString($var, True);
        $this->peer_sdp_m_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 peer_sdp_m_line_index = 4;</code>
     * @return int
     */
    public function getPeerSdpMLineIndex()
    {
        return $this->peer_sdp_m_line_index;
    }

    /**
     * Generated from protobuf field <code>uint32 peer_sdp_m_line_index = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPeerSdpMLineIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->peer_sdp_m_line_index = $var;

        return $this;
    }

}

