<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingOffer.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingOffer</code>
 */
class SignalingOffer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>uint64 called_user_id = 2;</code>
     */
    private $called_user_id = 0;
    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 3;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string caller_sdp = 4;</code>
     */
    private $caller_sdp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type int|string $called_user_id
     *     @type int $type
     *     @type string $caller_sdp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SignalingOffer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 called_user_id = 2;</code>
     * @return int|string
     */
    public function getCalledUserId()
    {
        return $this->called_user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 called_user_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCalledUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->called_user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Proto\SignalingOffer_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string caller_sdp = 4;</code>
     * @return string
     */
    public function getCallerSdp()
    {
        return $this->caller_sdp;
    }

    /**
     * Generated from protobuf field <code>string caller_sdp = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCallerSdp($var)
    {
        GPBUtil::checkString($var, True);
        $this->caller_sdp = $var;

        return $this;
    }

}

