<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileCheckUsername.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserProfileCheckUsernameResponse\Status instead.
     * @deprecated
     */
    class UserProfileCheckUsernameResponse_Status {}
}
class_exists(UserProfileCheckUsernameResponse\Status::class);
@trigger_error('Proto\UserProfileCheckUsernameResponse_Status is deprecated and will be removed in the next major release. Use Proto\UserProfileCheckUsernameResponse\Status instead', E_USER_DEPRECATED);

