<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserGetDeleteToken.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserGetDeleteTokenResponse</code>
 */
class UserGetDeleteTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>uint32 resend_delay = 2;</code>
     */
    private $resend_delay = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 3;</code>
     */
    private $sms_number;
    /**
     * Generated from protobuf field <code>string token_regex = 4;</code>
     */
    private $token_regex = '';
    /**
     * Generated from protobuf field <code>string token_length = 5;</code>
     */
    private $token_length = '';

    public function __construct() {
        \GPBMetadata\UserGetDeleteToken::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 resend_delay = 2;</code>
     * @return int
     */
    public function getResendDelay()
    {
        return $this->resend_delay;
    }

    /**
     * Generated from protobuf field <code>uint32 resend_delay = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setResendDelay($var)
    {
        GPBUtil::checkUint32($var);
        $this->resend_delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSmsNumber()
    {
        return $this->sms_number;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSmsNumber($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->sms_number = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_regex = 4;</code>
     * @return string
     */
    public function getTokenRegex()
    {
        return $this->token_regex;
    }

    /**
     * Generated from protobuf field <code>string token_regex = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenRegex($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_regex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_length = 5;</code>
     * @return string
     */
    public function getTokenLength()
    {
        return $this->token_length;
    }

    /**
     * Generated from protobuf field <code>string token_length = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenLength($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_length = $var;

        return $this;
    }

}

