<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsDelete.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserContactsDeleteResponse</code>
 */
class UserContactsDeleteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>uint64 phone = 2;</code>
     */
    private $phone = 0;

    public function __construct() {
        \GPBMetadata\UserContactsDelete::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 phone = 2;</code>
     * @return int|string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>uint64 phone = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkUint64($var);
        $this->phone = $var;

        return $this;
    }

}

