<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserVerifyNewDevice.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserVerifyNewDeviceResponse</code>
 */
class UserVerifyNewDeviceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     */
    private $app_name = '';
    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     */
    private $app_id = 0;
    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     */
    private $app_build_version = 0;
    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     */
    private $app_version = '';
    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     */
    private $platform = 0;
    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     */
    private $platform_version = '';
    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     */
    private $device = 0;
    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     */
    private $device_name = '';
    /**
     * Generated from protobuf field <code>bool two_step_verification = 10;</code>
     */
    private $two_step_verification = false;

    public function __construct() {
        \GPBMetadata\UserVerifyNewDevice::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @return string
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * Generated from protobuf field <code>string app_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     * @return int
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Generated from protobuf field <code>uint32 app_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     * @return int
     */
    public function getAppBuildVersion()
    {
        return $this->app_build_version;
    }

    /**
     * Generated from protobuf field <code>uint32 app_build_version = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAppBuildVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->app_build_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     * @return string
     */
    public function getAppVersion()
    {
        return $this->app_version;
    }

    /**
     * Generated from protobuf field <code>string app_version = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     * Generated from protobuf field <code>.proto.Platform platform = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkEnum($var, \Proto\Platform::class);
        $this->platform = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     * @return string
     */
    public function getPlatformVersion()
    {
        return $this->platform_version;
    }

    /**
     * Generated from protobuf field <code>string platform_version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->platform_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     * @return int
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * Generated from protobuf field <code>.proto.Device device = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkEnum($var, \Proto\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     * @return string
     */
    public function getDeviceName()
    {
        return $this->device_name;
    }

    /**
     * Generated from protobuf field <code>string device_name = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool two_step_verification = 10;</code>
     * @return bool
     */
    public function getTwoStepVerification()
    {
        return $this->two_step_verification;
    }

    /**
     * Generated from protobuf field <code>bool two_step_verification = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setTwoStepVerification($var)
    {
        GPBUtil::checkBool($var);
        $this->two_step_verification = $var;

        return $this;
    }

}

