<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserRegister.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserRegisterResponse</code>
 */
class UserRegisterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    private $username = '';
    /**
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     */
    private $user_id = 0;
    /**
     * Generated from protobuf field <code>string author_hash = 4;</code>
     */
    private $author_hash = '';
    /**
     * Generated from protobuf field <code>.proto.UserRegisterResponse.Method method = 5;</code>
     */
    private $method = 0;
    /**
     * Generated from protobuf field <code>uint32 resend_delay = 6;</code>
     */
    private $resend_delay = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 7;</code>
     */
    private $sms_number;
    /**
     * Generated from protobuf field <code>string verify_code_regex = 8;</code>
     */
    private $verify_code_regex = '';
    /**
     * Generated from protobuf field <code>uint32 verify_code_digit_count = 9;</code>
     */
    private $verify_code_digit_count = 0;

    public function __construct() {
        \GPBMetadata\UserRegister::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string author_hash = 4;</code>
     * @return string
     */
    public function getAuthorHash()
    {
        return $this->author_hash;
    }

    /**
     * Generated from protobuf field <code>string author_hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->author_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.UserRegisterResponse.Method method = 5;</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>.proto.UserRegisterResponse.Method method = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Proto\UserRegisterResponse_Method::class);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 resend_delay = 6;</code>
     * @return int
     */
    public function getResendDelay()
    {
        return $this->resend_delay;
    }

    /**
     * Generated from protobuf field <code>uint32 resend_delay = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setResendDelay($var)
    {
        GPBUtil::checkUint32($var);
        $this->resend_delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSmsNumber()
    {
        return $this->sms_number;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 sms_number = 7;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSmsNumber($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->sms_number = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verify_code_regex = 8;</code>
     * @return string
     */
    public function getVerifyCodeRegex()
    {
        return $this->verify_code_regex;
    }

    /**
     * Generated from protobuf field <code>string verify_code_regex = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setVerifyCodeRegex($var)
    {
        GPBUtil::checkString($var, True);
        $this->verify_code_regex = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 verify_code_digit_count = 9;</code>
     * @return int
     */
    public function getVerifyCodeDigitCount()
    {
        return $this->verify_code_digit_count;
    }

    /**
     * Generated from protobuf field <code>uint32 verify_code_digit_count = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setVerifyCodeDigitCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->verify_code_digit_count = $var;

        return $this;
    }

}

