<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserReport.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\UserReport\Reason</code>
 */
class UserReport_Reason
{
    /**
     * Generated from protobuf enum <code>OTHER = 0;</code>
     */
    const OTHER = 0;
    /**
     * Generated from protobuf enum <code>SPAM = 1;</code>
     */
    const SPAM = 1;
    /**
     * Generated from protobuf enum <code>ABUSE = 2;</code>
     */
    const ABUSE = 2;
    /**
     * Generated from protobuf enum <code>FAKE_ACCOUNT = 3;</code>
     */
    const FAKE_ACCOUNT = 3;
}

