<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDelete.proto

namespace Proto;

/**
 * Protobuf enum <code>Proto\UserDelete\Reason</code>
 */
class UserDelete_Reason
{
    /**
     * Generated from protobuf enum <code>OTHER = 0;</code>
     */
    const OTHER = 0;
}

