<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileGetSelfRemove.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserProfileGetSelfRemoveResponse</code>
 */
class UserProfileGetSelfRemoveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     */
    private $self_remove = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type int $self_remove
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserProfileGetSelfRemove::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     * @return int
     */
    public function getSelfRemove()
    {
        return $this->self_remove;
    }

    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSelfRemove($var)
    {
        GPBUtil::checkUint32($var);
        $this->self_remove = $var;

        return $this;
    }

}

