<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserUpdateStatus.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserUpdateStatus\Status instead.
     * @deprecated
     */
    class UserUpdateStatus_Status {}
}
class_exists(UserUpdateStatus\Status::class);
@trigger_error('Proto\UserUpdateStatus_Status is deprecated and will be removed in the next major release. Use Proto\UserUpdateStatus\Status instead', E_USER_DEPRECATED);

