<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserReport.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserReport\Reason instead.
     * @deprecated
     */
    class UserReport_Reason {}
}
class_exists(UserReport\Reason::class);
@trigger_error('Proto\UserReport_Reason is deprecated and will be removed in the next major release. Use Proto\UserReport\Reason instead', E_USER_DEPRECATED);

