<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserSessionGetActiveList.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserSessionGetActiveListResponse</code>
 */
class UserSessionGetActiveListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     */
    private $session;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\UserSessionGetActiveListResponse\Session[]|\Google\Protobuf\Internal\RepeatedField $session
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserSessionGetActiveList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UserSessionGetActiveListResponse.Session session = 2;</code>
     * @param \Proto\UserSessionGetActiveListResponse\Session[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSession($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\UserSessionGetActiveListResponse\Session::class);
        $this->session = $arr;

        return $this;
    }

}

