<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserDelete.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserDelete\Reason instead.
     * @deprecated
     */
    class UserDelete_Reason {}
}
class_exists(UserDelete\Reason::class);
@trigger_error('Proto\UserDelete_Reason is deprecated and will be removed in the next major release. Use Proto\UserDelete\Reason instead', E_USER_DEPRECATED);

