<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationRequestRecoveryToken.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserTwoStepVerificationRequestRecoveryTokenResponse</code>
 */
class UserTwoStepVerificationRequestRecoveryTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string email_pattern = 2;</code>
     */
    private $email_pattern = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type string $email_pattern
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserTwoStepVerificationRequestRecoveryToken::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email_pattern = 2;</code>
     * @return string
     */
    public function getEmailPattern()
    {
        return $this->email_pattern;
    }

    /**
     * Generated from protobuf field <code>string email_pattern = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmailPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_pattern = $var;

        return $this;
    }

}

