<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserAvatarAdd.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserAvatarAddResponse</code>
 */
class UserAvatarAddResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 2;</code>
     */
    private $avatar = null;

    public function __construct() {
        \GPBMetadata\UserAvatarAdd::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 2;</code>
     * @return \Proto\Avatar
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>.proto.Avatar avatar = 2;</code>
     * @param \Proto\Avatar $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkMessage($var, \Proto\Avatar::class);
        $this->avatar = $var;

        return $this;
    }

}

