<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsImport.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserContactsImportResponse\Contact instead.
     * @deprecated
     */
    class UserContactsImportResponse_Contact {}
}
class_exists(UserContactsImportResponse\Contact::class);
@trigger_error('Proto\UserContactsImportResponse_Contact is deprecated and will be removed in the next major release. Use Proto\UserContactsImportResponse\Contact instead', E_USER_DEPRECATED);

