<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsImport.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserContactsImportResponse</code>
 */
class UserContactsImportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.UserContactsImportResponse.Contact registered_contacts = 2;</code>
     */
    private $registered_contacts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\UserContactsImportResponse\Contact[]|\Google\Protobuf\Internal\RepeatedField $registered_contacts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserContactsImport::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UserContactsImportResponse.Contact registered_contacts = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegisteredContacts()
    {
        return $this->registered_contacts;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.UserContactsImportResponse.Contact registered_contacts = 2;</code>
     * @param \Proto\UserContactsImportResponse\Contact[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegisteredContacts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\UserContactsImportResponse\Contact::class);
        $this->registered_contacts = $arr;

        return $this;
    }

}

