<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsGetList.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserContactsGetListResponse</code>
 */
class UserContactsGetListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>repeated .proto.RegisteredUser registered_user = 2;</code>
     */
    private $registered_user;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Response $response
     *     @type \Proto\RegisteredUser[]|\Google\Protobuf\Internal\RepeatedField $registered_user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserContactsGetList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.RegisteredUser registered_user = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRegisteredUser()
    {
        return $this->registered_user;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.RegisteredUser registered_user = 2;</code>
     * @param \Proto\RegisteredUser[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRegisteredUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\RegisteredUser::class);
        $this->registered_user = $arr;

        return $this;
    }

}

