<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserContactsGetBlockedList.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserContactsGetBlockedListResponse\User instead.
     * @deprecated
     */
    class UserContactsGetBlockedListResponse_User {}
}
class_exists(UserContactsGetBlockedListResponse\User::class);
@trigger_error('Proto\UserContactsGetBlockedListResponse_User is deprecated and will be removed in the next major release. Use Proto\UserContactsGetBlockedListResponse\User instead', E_USER_DEPRECATED);

