<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationChangeRecoveryQuestion.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserTwoStepVerificationChangeRecoveryQuestion</code>
 */
class UserTwoStepVerificationChangeRecoveryQuestion extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>string password = 2;</code>
     */
    private $password = '';
    /**
     * Generated from protobuf field <code>string question_one = 3;</code>
     */
    private $question_one = '';
    /**
     * Generated from protobuf field <code>string answer_one = 4;</code>
     */
    private $answer_one = '';
    /**
     * Generated from protobuf field <code>string question_two = 5;</code>
     */
    private $question_two = '';
    /**
     * Generated from protobuf field <code>string answer_two = 6;</code>
     */
    private $answer_two = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type string $password
     *     @type string $question_one
     *     @type string $answer_one
     *     @type string $question_two
     *     @type string $answer_two
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserTwoStepVerificationChangeRecoveryQuestion::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string question_one = 3;</code>
     * @return string
     */
    public function getQuestionOne()
    {
        return $this->question_one;
    }

    /**
     * Generated from protobuf field <code>string question_one = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionOne($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_one = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string answer_one = 4;</code>
     * @return string
     */
    public function getAnswerOne()
    {
        return $this->answer_one;
    }

    /**
     * Generated from protobuf field <code>string answer_one = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswerOne($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer_one = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string question_two = 5;</code>
     * @return string
     */
    public function getQuestionTwo()
    {
        return $this->question_two;
    }

    /**
     * Generated from protobuf field <code>string question_two = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestionTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_two = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string answer_two = 6;</code>
     * @return string
     */
    public function getAnswerTwo()
    {
        return $this->answer_two;
    }

    /**
     * Generated from protobuf field <code>string answer_two = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswerTwo($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer_two = $var;

        return $this;
    }

}

