<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileSetSelfRemove.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserProfileSetSelfRemove</code>
 */
class UserProfileSetSelfRemove extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     */
    private $self_remove = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Request $request
     *     @type int $self_remove
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\UserProfileSetSelfRemove::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @return \Proto\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.proto.Request request = 1;</code>
     * @param \Proto\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Proto\Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     * @return int
     */
    public function getSelfRemove()
    {
        return $this->self_remove;
    }

    /**
     * Generated from protobuf field <code>uint32 self_remove = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSelfRemove($var)
    {
        GPBUtil::checkUint32($var);
        $this->self_remove = $var;

        return $this;
    }

}

