<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserRegister.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserRegisterResponse\Method instead.
     * @deprecated
     */
    class UserRegisterResponse_Method {}
}
class_exists(UserRegisterResponse\Method::class);
@trigger_error('Proto\UserRegisterResponse_Method is deprecated and will be removed in the next major release. Use Proto\UserRegisterResponse\Method instead', E_USER_DEPRECATED);

