<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserSessionGetActiveList.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\UserSessionGetActiveListResponse\Session instead.
     * @deprecated
     */
    class UserSessionGetActiveListResponse_Session {}
}
class_exists(UserSessionGetActiveListResponse\Session::class);
@trigger_error('Proto\UserSessionGetActiveListResponse_Session is deprecated and will be removed in the next major release. Use Proto\UserSessionGetActiveListResponse\Session instead', E_USER_DEPRECATED);

