<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserTwoStepVerificationChangeRecoveryEmail.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserTwoStepVerificationChangeRecoveryEmailResponse</code>
 */
class UserTwoStepVerificationChangeRecoveryEmailResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>string unconfirmed_email_pattern = 2;</code>
     */
    private $unconfirmed_email_pattern = '';

    public function __construct() {
        \GPBMetadata\UserTwoStepVerificationChangeRecoveryEmail::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @return \Proto\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.proto.Response response = 1;</code>
     * @param \Proto\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Proto\Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unconfirmed_email_pattern = 2;</code>
     * @return string
     */
    public function getUnconfirmedEmailPattern()
    {
        return $this->unconfirmed_email_pattern;
    }

    /**
     * Generated from protobuf field <code>string unconfirmed_email_pattern = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUnconfirmedEmailPattern($var)
    {
        GPBUtil::checkString($var, True);
        $this->unconfirmed_email_pattern = $var;

        return $this;
    }

}

