<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientResolveUsername.proto

namespace Proto\ClientResolveUsernameResponse;

/**
 * Protobuf type <code>proto.ClientResolveUsernameResponse.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>USER = 0;</code>
     */
    const USER = 0;
    /**
     * Generated from protobuf enum <code>ROOM = 1;</code>
     */
    const ROOM = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\ClientResolveUsernameResponse_Type::class);

