<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Global.proto

namespace Proto\RoomMessageLog;

/**
 * Protobuf type <code>proto.RoomMessageLog.ExtraType</code>
 */
class ExtraType
{
    /**
     * Generated from protobuf enum <code>NO_EXTRA = 0;</code>
     */
    const NO_EXTRA = 0;
    /**
     * Generated from protobuf enum <code>TARGET_USER = 1;</code>
     */
    const TARGET_USER = 1;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExtraType::class, \Proto\RoomMessageLog_ExtraType::class);

