<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingOffer.proto

namespace Proto\SignalingOffer;

/**
 * Protobuf type <code>proto.SignalingOffer.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>VOICE_CALLING = 0;</code>
     */
    const VOICE_CALLING = 0;
    /**
     * Generated from protobuf enum <code>VIDEO_CALLING = 1;</code>
     */
    const VIDEO_CALLING = 1;
    /**
     * Generated from protobuf enum <code>SCREEN_SHARING = 2;</code>
     */
    const SCREEN_SHARING = 2;
    /**
     * Generated from protobuf enum <code>SECRET_CHAT = 3;</code>
     */
    const SECRET_CHAT = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Proto\SignalingOffer_Type::class);

