<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignalingGetLog.proto

namespace Proto\SignalingGetLogResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.SignalingGetLogResponse.SignalingLog</code>
 */
class SignalingLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 2;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.proto.SignalingGetLogResponse.SignalingLog.Status status = 3;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 4;</code>
     */
    private $peer = null;
    /**
     * Generated from protobuf field <code>uint32 offer_time = 5;</code>
     */
    private $offer_time = 0;
    /**
     * Generated from protobuf field <code>uint32 duration = 6;</code>
     */
    private $duration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int $type
     *     @type int $status
     *     @type \Proto\RegisteredUser $peer
     *     @type int $offer_time
     *     @type int $duration
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SignalingGetLog::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingOffer.Type type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Proto\SignalingOffer_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingGetLogResponse.SignalingLog.Status status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.proto.SignalingGetLogResponse.SignalingLog.Status status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Proto\SignalingGetLogResponse_SignalingLog_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 4;</code>
     * @return \Proto\RegisteredUser
     */
    public function getPeer()
    {
        return $this->peer;
    }

    /**
     * Generated from protobuf field <code>.proto.RegisteredUser peer = 4;</code>
     * @param \Proto\RegisteredUser $var
     * @return $this
     */
    public function setPeer($var)
    {
        GPBUtil::checkMessage($var, \Proto\RegisteredUser::class);
        $this->peer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 offer_time = 5;</code>
     * @return int
     */
    public function getOfferTime()
    {
        return $this->offer_time;
    }

    /**
     * Generated from protobuf field <code>uint32 offer_time = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOfferTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->offer_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 6;</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SignalingLog::class, \Proto\SignalingGetLogResponse_SignalingLog::class);

