<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientRoomReport.proto

namespace Proto\ClientRoomReport;

/**
 * Protobuf type <code>proto.ClientRoomReport.Reason</code>
 */
class Reason
{
    /**
     * Generated from protobuf enum <code>OTHER = 0;</code>
     */
    const OTHER = 0;
    /**
     * Generated from protobuf enum <code>SPAM = 1;</code>
     */
    const SPAM = 1;
    /**
     * Generated from protobuf enum <code>PORNOGRAPHY = 2;</code>
     */
    const PORNOGRAPHY = 2;
    /**
     * Generated from protobuf enum <code>VIOLENCE = 3;</code>
     */
    const VIOLENCE = 3;
    /**
     * Generated from protobuf enum <code>ABUSE = 4;</code>
     */
    const ABUSE = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Reason::class, \Proto\ClientRoomReport_Reason::class);

